// src/config/servicesConfig.js

export const FIELD_TYPES = {
  TEXT: "text",
  NUMBER: "number",
  TOGGLE: "toggle",
  DROPDOWN: "dropdown",
  MULTISELECT: "multiselect",
  TEXTAREA: "textarea",
  ARRAY: "array",
  OBJECT: "object",
};

// Field sections for better organization
export const FIELD_SECTIONS = {
  BASIC: "basic",
  NETWORK: "network",
  COMPUTE: "compute",
  STORAGE: "storage",
  SECURITY: "security",
  BACKUP: "backup",
  MONITORING: "monitoring",
  ADVANCED: "advanced",
};

export const SERVICES_CONFIG = {
  // AWS Services
  vpc: {
    name: "vpc",
    displayName: "Virtual Private Cloud (VPC)",
    description: "AWS Virtual Private Cloud for network isolation",
    provider: "aws",
    category: "Networking",
    icon: "🌐",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable VPC",
        description: "Enable VPC service",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      cidr: {
        type: FIELD_TYPES.TEXT,
        name: "cidr",
        displayName: "CIDR Block",
        description: "The IPv4 CIDR block for the VPC",
        defaultValue: "10.0.0.0/16",
        validation: { pattern: /^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/ },
        placeholder: "10.0.0.0/16",
        helpText: "Example: 10.0.0.0/16 provides 65,536 IP addresses",
        section: FIELD_SECTIONS.NETWORK,
      },
      azCount: {
        type: FIELD_TYPES.DROPDOWN,
        name: "azCount",
        displayName: "Availability Zones",
        description: "Number of availability zones to use for high availability",
        defaultValue: 2,
        options: [
          { value: 1, label: "1 AZ (Development only)" },
          { value: 2, label: "2 AZs (Recommended)" },
          { value: 3, label: "3 AZs (High availability)" },
        ],
        helpText: "Use at least 2 AZs for production workloads",
        section: FIELD_SECTIONS.NETWORK,
      },
      createPublicSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createPublicSubnets",
        displayName: "Public Subnets",
        description: "Create public subnets with internet access",
        defaultValue: true,
        helpText: "Required for load balancers and NAT gateways",
        section: FIELD_SECTIONS.NETWORK,
      },
      createPrivateSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createPrivateSubnets",
        displayName: "Private Subnets",
        description: "Create private subnets for internal resources",
        defaultValue: true,
        helpText: "Recommended for application and database tiers",
        section: FIELD_SECTIONS.NETWORK,
      },
      createIntraSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createIntraSubnets",
        displayName: "Intra Subnets",
        description: "Create isolated subnets with no internet access",
        defaultValue: false,
        helpText: "For completely isolated resources (no NAT gateway)",
        section: FIELD_SECTIONS.NETWORK,
      },
      createDatabaseSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createDatabaseSubnets",
        displayName: "Database Subnets",
        description: "Create dedicated subnets for databases",
        defaultValue: true,
        helpText: "Required for RDS, Aurora, and ElastiCache",
        section: FIELD_SECTIONS.NETWORK,
        dependsOn: { field: "createPrivateSubnets", value: true },
      },
      createDatabaseSubnetGroup: {
        type: FIELD_TYPES.TOGGLE,
        name: "createDatabaseSubnetGroup",
        displayName: "DB Subnet Group",
        description: "Create RDS/Aurora subnet group automatically",
        defaultValue: true,
        section: FIELD_SECTIONS.NETWORK,
        dependsOn: { field: "createDatabaseSubnets", value: true },
      },
      natGateway: {
        type: FIELD_TYPES.DROPDOWN,
        name: "natGateway",
        displayName: "NAT Gateway Strategy",
        description: "How to provision NAT gateways for private subnet internet access",
        defaultValue: "SINGLE",
        options: [
          { value: "NO_NAT", label: "None - No internet for private subnets" },
          { value: "SINGLE", label: "Single - Cost-effective (not HA)" },
          { value: "ONE_PER_AZ", label: "One per AZ - High availability (recommended)" },
          { value: "ONE_PER_SUBNET", label: "One per subnet - Maximum redundancy" },
        ],
        helpText: "Single NAT saves cost but creates a single point of failure",
        section: FIELD_SECTIONS.NETWORK,
        dependsOn: { field: "createPrivateSubnets", value: true },
      },
      publicSubnetTags: {
        type: FIELD_TYPES.OBJECT,
        name: "publicSubnetTags",
        displayName: "Public Subnet Tags",
        description: "Additional AWS tags for public subnets (JSON)",
        helpText: 'Example: {"Environment": "prod", "Team": "platform"}',
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "createPublicSubnets", value: true },
      },
      privateSubnetTags: {
        type: FIELD_TYPES.OBJECT,
        name: "privateSubnetTags",
        displayName: "Private Subnet Tags",
        description: "Additional AWS tags for private subnets (JSON)",
        helpText: 'Example: {"Environment": "prod", "Team": "platform"}',
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "createPrivateSubnets", value: true },
      },
      databaseSubnetTags: {
        type: FIELD_TYPES.OBJECT,
        name: "databaseSubnetTags",
        displayName: "Database Subnet Tags",
        description: "Additional AWS tags for database subnets (JSON)",
        helpText: 'Example: {"Environment": "prod", "Team": "database"}',
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "createDatabaseSubnets", value: true },
      },
      enableVpnGateway: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableVpnGateway",
        displayName: "VPN Gateway",
        description: "Enable VPN Gateway for hybrid cloud connectivity",
        defaultValue: false,
        helpText: "Required for Site-to-Site VPN connections",
        section: FIELD_SECTIONS.ADVANCED,
      },
      enableFlowLogs: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableFlowLogs",
        displayName: "VPC Flow Logs",
        description: "Enable flow logs for network traffic analysis",
        defaultValue: false,
        helpText: "Useful for security and network troubleshooting (additional cost)",
        section: FIELD_SECTIONS.MONITORING,
      },
      enableDnsHostnames: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDnsHostnames",
        displayName: "DNS Hostnames",
        description: "Enable DNS hostname resolution in VPC",
        defaultValue: true,
        helpText: "Required for many AWS services",
        section: FIELD_SECTIONS.ADVANCED,
      },
      enableDnsSupport: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDnsSupport",
        displayName: "DNS Support",
        description: "Enable DNS resolution in VPC",
        defaultValue: true,
        helpText: "Required for Route53 private hosted zones",
        section: FIELD_SECTIONS.ADVANCED,
      },
    },
  },

  eks: {
    name: "eks",
    displayName: "Elastic Kubernetes Service (EKS)",
    description: "Managed Kubernetes service from AWS",
    provider: "aws",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable EKS",
        description: "Enable EKS service",
        defaultValue: false,
      },
      kubernetesVersion: {
        type: FIELD_TYPES.DROPDOWN,
        name: "kubernetesVersion",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.34",
        options: [
          { value: "1.30", label: "1.30" },
          { value: "1.31", label: "1.31" },
          { value: "1.32", label: "1.32" },
          { value: "1.33", label: "1.33" },
          { value: "1.34", label: "1.34" },
        ],
      },
      enableClusterCreatorAdminPermissions: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableClusterCreatorAdminPermissions",
        displayName: "Cluster Creator Admin",
        description: "Enable cluster creator admin permissions",
        defaultValue: true,
      },
      endpointPublicAccess: {
        type: FIELD_TYPES.TOGGLE,
        name: "endpointPublicAccess",
        displayName: "Public Endpoint",
        description: "Enable public access to cluster endpoint",
        defaultValue: true,
      },
      authenticationMode: {
        type: FIELD_TYPES.DROPDOWN,
        name: "authenticationMode",
        displayName: "Authentication Mode",
        description: "Authentication mode for the cluster",
        defaultValue: "API",
        options: [
          { value: "API", label: "API" },
          { value: "API_AND_CONFIG_MAP", label: "API and ConfigMap" },
          { value: "CONFIG_MAP", label: "ConfigMap" },
        ],
      },
      enableIrsa: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableIrsa",
        displayName: "IRSA",
        description: "Enable IAM Roles for Service Accounts",
        defaultValue: true,
      },
      defaultNodeGroupAmiType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "defaultNodeGroupAmiType",
        displayName: "AMI Type",
        description: "AMI type for node group",
        defaultValue: "BOTTLEROCKET_ARM_64",
        options: [
          { value: "AL2_x86_64", label: "Amazon Linux 2 (x86_64)" },
          {
            value: "AL2_x86_64_GPU",
            label: "Amazon Linux 2 GPU (x86_64)",
          },
          { value: "AL2_ARM_64", label: "Amazon Linux 2 (ARM64)" },
          {
            value: "BOTTLEROCKET_ARM_64",
            label: "Bottlerocket (ARM64)",
          },
          {
            value: "BOTTLEROCKET_x86_64",
            label: "Bottlerocket (x86_64)",
          },
        ],
      },
      defaultNodeGroupInstanceTypes: {
        type: FIELD_TYPES.MULTISELECT,
        name: "defaultNodeGroupInstanceTypes",
        displayName: "Instance Types",
        description: "EC2 instance types",
        defaultValue: ["t4g.large"],
        options: [
          { value: "t3.micro", label: "t3.micro" },
          { value: "t3.small", label: "t3.small" },
          { value: "t3.medium", label: "t3.medium" },
          { value: "t3.large", label: "t3.large" },
          { value: "t4g.medium", label: "t4g.medium" },
          { value: "t4g.large", label: "t4g.large" },
          { value: "m5.large", label: "m5.large" },
          { value: "m5.xlarge", label: "m5.xlarge" },
        ],
      },
      defaultNodeGroupCapacityType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "defaultNodeGroupCapacityType",
        displayName: "Capacity Type",
        description: "Capacity type for node group",
        defaultValue: "ON_DEMAND",
        options: [
          { value: "ON_DEMAND", label: "On-Demand" },
          { value: "SPOT", label: "Spot" },
        ],
      },
      defaultNodeGroupMinSize: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupMinSize",
        displayName: "Min Nodes",
        description: "Minimum number of nodes",
        defaultValue: 1,
        min: 0,
        max: 100,
      },
      defaultNodeGroupMaxSize: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupMaxSize",
        displayName: "Max Nodes",
        description: "Maximum number of nodes",
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      defaultNodeGroupDesiredSize: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupDesiredSize",
        displayName: "Desired Nodes",
        description: "Desired number of nodes",
        defaultValue: 2,
        min: 0,
        max: 100,
      },
      defaultNodeGroupMaxUnavailable: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupMaxUnavailable",
        displayName: "Max Unavailable",
        description: "Max unavailable nodes during updates",
        defaultValue: 1,
        min: 1,
        max: 10,
      },
      karpenterEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "karpenterEnabled",
        displayName: "Enable Karpenter",
        description: "Enable Karpenter node autoscaler",
        defaultValue: true,
      },
      karpenterNodepoolArch: {
        type: FIELD_TYPES.DROPDOWN,
        name: "karpenterNodepoolArch",
        displayName: "Karpenter Architecture",
        description: "Default Karpenter nodepool architecture",
        defaultValue: "arm64",
        options: [
          { value: "amd64", label: "AMD64 (x86_64)" },
          { value: "arm64", label: "ARM64" },
        ],
      },
      karpenterNodepoolCapacityType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "karpenterNodepoolCapacityType",
        displayName: "Karpenter Capacity Type",
        description: "Default Karpenter capacity type",
        defaultValue: "spot",
        options: [
          { value: "on-demand", label: "On-Demand" },
          { value: "spot", label: "Spot" },
        ],
      },
    },
  },

  rds: {
    name: "rds",
    displayName: "Relational Database Service (RDS)",
    description: "Fully managed relational databases with automated backups",
    provider: "aws",
    category: "Database",
    icon: "🗄️",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable RDS",
        description: "Enable managed relational database",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      engine: {
        type: FIELD_TYPES.DROPDOWN,
        name: "engine",
        displayName: "Database Engine",
        description: "Choose your database engine",
        defaultValue: "postgres",
        options: [
          { value: "postgres", label: "PostgreSQL - Open-source, feature-rich" },
          { value: "mysql", label: "MySQL - Popular open-source" },
          { value: "mariadb", label: "MariaDB - MySQL fork" },
          { value: "oracle-ee", label: "Oracle Enterprise" },
          { value: "sqlserver-ex", label: "SQL Server Express" },
        ],
        section: FIELD_SECTIONS.BASIC,
      },
      version: {
        type: FIELD_TYPES.TEXT,
        name: "version",
        displayName: "Engine Version",
        description: "Database version",
        defaultValue: "15.4",
        placeholder: "15.4 for PostgreSQL, 8.0.35 for MySQL",
        section: FIELD_SECTIONS.BASIC,
      },
      majorEngineVersion: {
        type: FIELD_TYPES.TEXT,
        name: "majorEngineVersion",
        displayName: "Major Engine Version",
        description: "Major version for parameter group",
        defaultValue: "15.4",
        placeholder: "15 for PostgreSQL 15.x, 8.0 for MySQL 8.0.x",
        section: FIELD_SECTIONS.ADVANCED,
      },
      family: {
        type: FIELD_TYPES.TEXT,
        name: "family",
        displayName: "Parameter Group Family",
        description: "DB parameter group family",
        defaultValue: "postgres15",
        placeholder: "postgres15, mysql8.0, mariadb10.11",
        section: FIELD_SECTIONS.ADVANCED,
      },
      instanceClass: {
        type: FIELD_TYPES.DROPDOWN,
        name: "instanceClass",
        displayName: "Instance Class",
        description: "Database compute capacity",
        defaultValue: "db.t3.small",
        options: [
          { value: "db.t3.micro", label: "t3.micro - 1 vCPU, 1GB (Dev)" },
          { value: "db.t3.small", label: "t3.small - 2 vCPU, 2GB" },
          { value: "db.t3.medium", label: "t3.medium - 2 vCPU, 4GB" },
          { value: "db.t3.large", label: "t3.large - 2 vCPU, 8GB" },
          { value: "db.r5.large", label: "r5.large - 2 vCPU, 16GB (Memory-optimized)" },
          { value: "db.r5.xlarge", label: "r5.xlarge - 4 vCPU, 32GB" },
        ],
        helpText: "T3 for general use, R5 for memory-intensive workloads",
        section: FIELD_SECTIONS.COMPUTE,
      },
      allocatedStorage: {
        type: FIELD_TYPES.NUMBER,
        name: "allocatedStorage",
        displayName: "Storage (GB)",
        description: "Initial storage allocation",
        defaultValue: 20,
        min: 20,
        max: 1000,
        helpText: "Can auto-scale up to max storage",
        section: FIELD_SECTIONS.STORAGE,
      },
      maxAllocatedStorage: {
        type: FIELD_TYPES.NUMBER,
        name: "maxAllocatedStorage",
        displayName: "Max Storage (GB)",
        description: "Maximum storage for auto-scaling",
        defaultValue: 100,
        min: 20,
        max: 10000,
        helpText: "Enables storage autoscaling",
        section: FIELD_SECTIONS.STORAGE,
      },
      multiAz: {
        type: FIELD_TYPES.TOGGLE,
        name: "multiAz",
        displayName: "Multi-AZ Deployment",
        description: "Deploy standby in another AZ",
        defaultValue: false,
        helpText: "Recommended for production HA",
        section: FIELD_SECTIONS.ADVANCED,
      },
      backupRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "backupRetention",
        displayName: "Backup Retention (days)",
        description: "Automated backup retention",
        defaultValue: 7,
        min: 0,
        max: 35,
        helpText: "Set to 0 to disable automated backups",
        section: FIELD_SECTIONS.BACKUP,
      },
      backupWindow: {
        type: FIELD_TYPES.TEXT,
        name: "backupWindow",
        displayName: "Backup Window",
        description: "Daily backup time window (UTC)",
        defaultValue: "03:00-06:00",
        placeholder: "03:00-06:00",
        helpText: "Choose low-traffic period",
        section: FIELD_SECTIONS.BACKUP,
      },
      maintenanceWindow: {
        type: FIELD_TYPES.TEXT,
        name: "maintenanceWindow",
        displayName: "Maintenance Window",
        description: "Weekly maintenance window (UTC)",
        defaultValue: "Mon:00:00-Mon:03:00",
        placeholder: "Mon:00:00-Mon:03:00",
        section: FIELD_SECTIONS.ADVANCED,
      },
      deletionProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "deletionProtection",
        displayName: "Deletion Protection",
        description: "Prevent accidental deletion",
        defaultValue: false,
        helpText: "Recommended for production",
        section: FIELD_SECTIONS.SECURITY,
      },
      skipFinalSnapshot: {
        type: FIELD_TYPES.TOGGLE,
        name: "skipFinalSnapshot",
        displayName: "Skip Final Snapshot",
        description: "Skip snapshot on deletion",
        defaultValue: true,
        helpText: "Set false for production databases",
        section: FIELD_SECTIONS.BACKUP,
      },
      applyImmediately: {
        type: FIELD_TYPES.TOGGLE,
        name: "applyImmediately",
        displayName: "Apply Changes Immediately",
        description: "Apply changes without waiting for maintenance",
        defaultValue: false,
        helpText: "May cause brief downtime",
        section: FIELD_SECTIONS.ADVANCED,
      },
      autoMinorVersionUpgrade: {
        type: FIELD_TYPES.TOGGLE,
        name: "autoMinorVersionUpgrade",
        displayName: "Auto Minor Version Upgrade",
        description: "Auto-apply minor patches",
        defaultValue: true,
        helpText: "Applies during maintenance window",
        section: FIELD_SECTIONS.ADVANCED,
      },
      publiclyAccessible: {
        type: FIELD_TYPES.TOGGLE,
        name: "publiclyAccessible",
        displayName: "Publicly Accessible",
        description: "Assign public IP address",
        defaultValue: false,
        helpText: "⚠️ Security risk - use VPN/bastion instead",
        section: FIELD_SECTIONS.SECURITY,
      },
      iamDatabaseAuthenticationEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "iamDatabaseAuthenticationEnabled",
        displayName: "IAM Authentication",
        description: "Enable IAM-based authentication",
        defaultValue: false,
        helpText: "Passwordless authentication via IAM",
        section: FIELD_SECTIONS.SECURITY,
      },
      manageMasterUserPassword: {
        type: FIELD_TYPES.TOGGLE,
        name: "manageMasterUserPassword",
        displayName: "AWS Managed Password",
        description: "Store password in Secrets Manager",
        defaultValue: false,
        helpText: "Automatic password rotation",
        section: FIELD_SECTIONS.SECURITY,
      },
      performanceInsights: {
        type: FIELD_TYPES.TOGGLE,
        name: "performanceInsights",
        displayName: "Performance Insights",
        description: "Database performance monitoring",
        defaultValue: false,
        helpText: "Recommended for troubleshooting",
        section: FIELD_SECTIONS.MONITORING,
      },
      performanceInsightsRetentionPeriod: {
        type: FIELD_TYPES.NUMBER,
        name: "performanceInsightsRetentionPeriod",
        displayName: "Insights Retention (days)",
        description: "Performance data retention",
        defaultValue: 7,
        min: 7,
        max: 731,
        section: FIELD_SECTIONS.MONITORING,
        dependsOn: { field: "performanceInsights", value: true },
      },
      monitoringInterval: {
        type: FIELD_TYPES.DROPDOWN,
        name: "monitoringInterval",
        displayName: "Enhanced Monitoring (seconds)",
        description: "OS metrics collection frequency",
        defaultValue: 0,
        options: [
          { value: 0, label: "Disabled" },
          { value: 1, label: "1 second (Most detailed)" },
          { value: 5, label: "5 seconds" },
          { value: 10, label: "10 seconds" },
          { value: 15, label: "15 seconds" },
          { value: 30, label: "30 seconds" },
          { value: 60, label: "60 seconds (Recommended)" },
        ],
        helpText: "Incurs additional CloudWatch costs",
        section: FIELD_SECTIONS.MONITORING,
      },
      deleteAutomatedBackups: {
        type: FIELD_TYPES.TOGGLE,
        name: "deleteAutomatedBackups",
        displayName: "Delete Automated Backups",
        description: "Delete backups when instance is deleted",
        defaultValue: true,
        section: FIELD_SECTIONS.BACKUP,
      },
    },
  },

  aurora: {
    name: "aurora",
    displayName: "Aurora Serverless",
    description: "Serverless relational database with auto-scaling",
    provider: "aws",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Aurora",
        description: "Enable Aurora Serverless service",
        defaultValue: false,
      },
      engine: {
        type: FIELD_TYPES.DROPDOWN,
        name: "engine",
        displayName: "Database Engine",
        description: "Aurora database engine",
        defaultValue: "aurora-postgresql",
        options: [
          { value: "aurora-postgresql", label: "Aurora PostgreSQL" },
          { value: "aurora-mysql", label: "Aurora MySQL" },
        ],
      },
      engineVersion: {
        type: FIELD_TYPES.TEXT,
        name: "engineVersion",
        displayName: "Engine Version",
        description: "Aurora engine version",
        defaultValue: "15.8",
      },
      instances: {
        type: FIELD_TYPES.OBJECT,
        name: "instances",
        displayName: "Aurora Instances",
        description: "Map of Aurora instances configuration",
        defaultValue: { one: {} },
      },
      serverlessv2MinCapacity: {
        type: FIELD_TYPES.NUMBER,
        name: "serverlessv2MinCapacity",
        displayName: "Min Capacity (ACU)",
        description: "Minimum Aurora Capacity Units",
        defaultValue: 0,
        min: 0,
        max: 128,
      },
      serverlessv2MaxCapacity: {
        type: FIELD_TYPES.NUMBER,
        name: "serverlessv2MaxCapacity",
        displayName: "Max Capacity (ACU)",
        description: "Maximum Aurora Capacity Units",
        defaultValue: 10,
        min: 0.5,
        max: 128,
      },
      serverlessv2SecondsUntilAutoPause: {
        type: FIELD_TYPES.NUMBER,
        name: "serverlessv2SecondsUntilAutoPause",
        displayName: "Seconds Until Auto Pause",
        description: "Seconds until Aurora Serverless auto-pauses",
        defaultValue: 3600,
        min: 300,
        max: 86400,
      },
      backupRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "backupRetention",
        displayName: "Backup Retention (days)",
        description: "Backup retention period in days",
        defaultValue: 7,
        min: 1,
        max: 35,
      },
      deletionProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "deletionProtection",
        displayName: "Deletion Protection",
        description: "Enable deletion protection",
        defaultValue: false,
      },
      enableHttpEndpoint: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableHttpEndpoint",
        displayName: "Data API",
        description: "Enable HTTP endpoint for Data API",
        defaultValue: true,
      },
      iamDatabaseAuthenticationEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "iamDatabaseAuthenticationEnabled",
        displayName: "IAM Database Authentication",
        description: "Enable IAM database authentication",
        defaultValue: true,
      },
      monitoringInterval: {
        type: FIELD_TYPES.DROPDOWN,
        name: "monitoringInterval",
        displayName: "Enhanced Monitoring Interval (seconds)",
        description: "Enhanced monitoring interval",
        defaultValue: 60,
        options: [
          { value: 0, label: "Disabled" },
          { value: 1, label: "1 second" },
          { value: 5, label: "5 seconds" },
          { value: 10, label: "10 seconds" },
          { value: 15, label: "15 seconds" },
          { value: 30, label: "30 seconds" },
          { value: 60, label: "60 seconds" },
        ],
      },
      applyImmediately: {
        type: FIELD_TYPES.TOGGLE,
        name: "applyImmediately",
        displayName: "Apply Immediately",
        description: "Apply changes immediately",
        defaultValue: true,
      },
      skipFinalSnapshot: {
        type: FIELD_TYPES.TOGGLE,
        name: "skipFinalSnapshot",
        displayName: "Skip Final Snapshot",
        description: "Skip final snapshot when deleting",
        defaultValue: true,
      },
      deleteAutomatedBackups: {
        type: FIELD_TYPES.TOGGLE,
        name: "deleteAutomatedBackups",
        displayName: "Delete Automated Backups",
        description: "Delete automated backups on cluster deletion",
        defaultValue: true,
      },
    },
  },

  // Azure Services
  vnet: {
    name: "vnet",
    displayName: "Virtual Network (VNet)",
    description: "Azure Virtual Network for network isolation",
    provider: "azure",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable VNet",
        description: "Enable VNet service",
        defaultValue: false,
      },
      addressSpace: {
        type: FIELD_TYPES.TEXT,
        name: "addressSpace",
        displayName: "Address Space",
        description: "The address space for the VNet",
        defaultValue: "10.0.0.0/16",
        validation: { pattern: /^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/ },
      },
      subnets: {
        type: FIELD_TYPES.OBJECT,
        name: "subnets",
        displayName: "Subnets",
        description: "Subnet configurations",
      },
      enableDdosProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDdosProtection",
        displayName: "DDoS Protection",
        description: "Enable DDoS protection",
        defaultValue: false,
      },
      enableVmProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableVmProtection",
        displayName: "VM Protection",
        description: "Enable VM protection",
        defaultValue: false,
      },
    },
  },

  aks: {
    name: "aks",
    displayName: "Azure Kubernetes Service (AKS)",
    description: "Managed Kubernetes service from Azure",
    provider: "azure",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable AKS",
        description: "Enable AKS service",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      nodeGroups: {
        type: FIELD_TYPES.NUMBER,
        name: "nodeGroups",
        displayName: "Node Pools",
        description: "Number of node pools",
        defaultValue: 1,
        min: 1,
        max: 10,
      },
      minNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "minNodes",
        displayName: "Min Nodes",
        description: "Minimum number of nodes",
        defaultValue: 2,
        min: 1,
        max: 100,
      },
      maxNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "maxNodes",
        displayName: "Max Nodes",
        description: "Maximum number of nodes",
        defaultValue: 5,
        min: 1,
        max: 100,
      },
      vmSize: {
        type: FIELD_TYPES.DROPDOWN,
        name: "vmSize",
        displayName: "VM Size",
        description: "Azure VM size",
        defaultValue: "Standard_D2s_v3",
        options: [
          { value: "Standard_B2s", label: "Standard_B2s" },
          { value: "Standard_D2s_v3", label: "Standard_D2s_v3" },
          { value: "Standard_D4s_v3", label: "Standard_D4s_v3" },
          { value: "Standard_D8s_v3", label: "Standard_D8s_v3" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "OS disk size in GB",
        defaultValue: 50,
        min: 30,
        max: 1000,
      },
      enableAutoScaling: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutoScaling",
        displayName: "Auto Scaling",
        description: "Enable node auto scaling",
        defaultValue: true,
      },
      enableClusterAutoscaler: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableClusterAutoscaler",
        displayName: "Cluster Autoscaler",
        description: "Enable cluster autoscaler",
        defaultValue: false,
      },
      enableMetricsServer: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableMetricsServer",
        displayName: "Metrics Server",
        description: "Enable metrics server",
        defaultValue: true,
      },
      addons: {
        type: FIELD_TYPES.OBJECT,
        name: "addons",
        displayName: "AKS Addons",
        description: "AKS managed addons",
      },
    },
  },

  sqlDatabase: {
    name: "sqlDatabase",
    displayName: "Azure SQL Database",
    description: "Managed SQL database service",
    provider: "azure",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable SQL Database",
        description: "Enable Azure SQL Database",
        defaultValue: false,
      },
      tier: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tier",
        displayName: "Service Tier",
        description: "Database service tier",
        defaultValue: "Basic",
        options: [
          { value: "Basic", label: "Basic" },
          { value: "Standard", label: "Standard" },
          { value: "Premium", label: "Premium" },
          { value: "GeneralPurpose", label: "General Purpose" },
          { value: "BusinessCritical", label: "Business Critical" },
        ],
      },
      size: {
        type: FIELD_TYPES.TEXT,
        name: "size",
        displayName: "Compute Size",
        description: "Database compute size",
        defaultValue: "S0",
      },
      maxStorage: {
        type: FIELD_TYPES.NUMBER,
        name: "maxStorage",
        displayName: "Max Storage (GB)",
        description: "Maximum storage in GB",
        defaultValue: 2,
        min: 1,
        max: 1000,
      },
      enableBackup: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableBackup",
        displayName: "Automated Backup",
        description: "Enable automated backup",
        defaultValue: true,
      },
      backupRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "backupRetention",
        displayName: "Backup Retention (days)",
        description: "Backup retention period in days",
        defaultValue: 7,
        min: 1,
        max: 35,
      },
      enableEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableEncryption",
        displayName: "Encryption",
        description: "Enable encryption at rest",
        defaultValue: true,
      },
      enableAdvancedThreatProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAdvancedThreatProtection",
        displayName: "Advanced Threat Protection",
        description: "Enable advanced threat protection",
        defaultValue: false,
      },
      enableAudit: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAudit",
        displayName: "Auditing",
        description: "Enable database auditing",
        defaultValue: false,
      },
    },
  },

  // More AWS Services
  opensearch: {
    name: "opensearch",
    displayName: "OpenSearch Service",
    description: "Managed search and analytics service",
    provider: "aws",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable OpenSearch",
        description: "Enable OpenSearch service",
        defaultValue: false,
      },
      domainName: {
        type: FIELD_TYPES.TEXT,
        name: "domainName",
        displayName: "Domain Name",
        description: "OpenSearch domain name",
        defaultValue: "opensearch",
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "OpenSearch Version",
        description: "OpenSearch version",
        defaultValue: "OpenSearch_2.19",
        options: [
          { value: "OpenSearch_2.19", label: "OpenSearch 2.19" },
          { value: "OpenSearch_2.11", label: "OpenSearch 2.11" },
          { value: "OpenSearch_2.9", label: "OpenSearch 2.9" },
          { value: "OpenSearch_1.3", label: "OpenSearch 1.3" },
        ],
      },
      instanceType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "instanceType",
        displayName: "Instance Type",
        description: "OpenSearch instance type",
        defaultValue: "m7g.medium.search",
        options: [
          { value: "t3.small.search", label: "t3.small.search" },
          { value: "t3.medium.search", label: "t3.medium.search" },
          { value: "m5.large.search", label: "m5.large.search" },
          { value: "m7g.medium.search", label: "m7g.medium.search" },
          { value: "m7g.large.search", label: "m7g.large.search" },
        ],
      },
      instanceCount: {
        type: FIELD_TYPES.NUMBER,
        name: "instanceCount",
        displayName: "Instance Count",
        description: "Number of data instances",
        defaultValue: 2,
        min: 1,
        max: 20,
        helpText: "Must be even number for multi-AZ deployment",
      },
      dedicatedMasterEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "dedicatedMasterEnabled",
        displayName: "Dedicated Master",
        description: "Enable dedicated master nodes",
        defaultValue: false,
      },
      dedicatedMasterType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "dedicatedMasterType",
        displayName: "Master Instance Type",
        description: "Master node instance type",
        defaultValue: "t3.small.search",
        options: [
          { value: "t3.small.search", label: "t3.small.search" },
          { value: "t3.medium.search", label: "t3.medium.search" },
          { value: "m5.large.search", label: "m5.large.search" },
        ],
      },
      dedicatedMasterCount: {
        type: FIELD_TYPES.NUMBER,
        name: "dedicatedMasterCount",
        displayName: "Master Node Count",
        description: "Number of master nodes",
        defaultValue: 0,
        min: 0,
        max: 5,
      },
      ebsEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "ebsEnabled",
        displayName: "EBS Storage",
        description: "Enable EBS storage volumes",
        defaultValue: true,
      },
      ebsVolumeSize: {
        type: FIELD_TYPES.NUMBER,
        name: "ebsVolumeSize",
        displayName: "EBS Volume Size (GB)",
        description: "EBS volume size per instance",
        defaultValue: 64,
        min: 10,
        max: 1000,
      },
      ebsVolumeType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "ebsVolumeType",
        displayName: "EBS Volume Type",
        description: "EBS volume type",
        defaultValue: "gp3",
        options: [
          { value: "gp3", label: "gp3" },
          { value: "gp2", label: "gp2" },
          { value: "io1", label: "io1" },
        ],
      },
      customEndpointEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "customEndpointEnabled",
        displayName: "Custom Endpoint",
        description: "Enable custom endpoint",
        defaultValue: false,
      },
      nodeToNodeEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "nodeToNodeEncryption",
        displayName: "Node-to-Node Encryption",
        description: "Enable node-to-node encryption",
        defaultValue: true,
      },
      enforceHttps: {
        type: FIELD_TYPES.TOGGLE,
        name: "enforceHttps",
        displayName: "Enforce HTTPS",
        description: "Enforce HTTPS for all traffic",
        defaultValue: true,
      },
      tlsSecurityPolicy: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tlsSecurityPolicy",
        displayName: "TLS Security Policy",
        description: "TLS security policy",
        defaultValue: "Policy-Min-TLS-1-2-2019-07",
        options: [
          {
            value: "Policy-Min-TLS-1-0-2019-07",
            label: "TLS 1.0 (Minimum)",
          },
          {
            value: "Policy-Min-TLS-1-2-2019-07",
            label: "TLS 1.2 (Minimum)",
          },
          {
            value: "Policy-Min-TLS-1-2-PFS-2023-10",
            label: "TLS 1.2 PFS",
          },
        ],
      },
      advancedSecurityEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "advancedSecurityEnabled",
        displayName: "Advanced Security",
        description: "Enable advanced security options",
        defaultValue: true,
      },
      internalUserDatabaseEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "internalUserDatabaseEnabled",
        displayName: "Internal User Database",
        description: "Enable internal user database",
        defaultValue: true,
      },
      masterUserName: {
        type: FIELD_TYPES.TEXT,
        name: "masterUserName",
        displayName: "Master User Name",
        description: "Master user name for authentication",
        defaultValue: "admin",
      },
      createAccessPolicy: {
        type: FIELD_TYPES.TOGGLE,
        name: "createAccessPolicy",
        displayName: "Create Access Policy",
        description: "Create domain access policy",
        defaultValue: true,
      },
      ipAddressType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "ipAddressType",
        displayName: "IP Address Type",
        description: "IP address type for the domain",
        defaultValue: "dualstack",
        options: [
          { value: "ipv4", label: "IPv4 only" },
          { value: "dualstack", label: "IPv4 and IPv6 (Dual Stack)" },
        ],
      },
      allowExplicitIndex: {
        type: FIELD_TYPES.TOGGLE,
        name: "allowExplicitIndex",
        displayName: "Allow Explicit Index",
        description: "Allow explicit index in multi-action requests",
        defaultValue: true,
      },
    },
  },

  ecr: {
    name: "ecr",
    displayName: "Elastic Container Registry (ECR)",
    description: "Managed Docker container registry with vulnerability scanning",
    provider: "aws",
    category: "Storage",
    icon: "🐳",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable ECR",
        description: "Enable container registry service",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      repositoryNames: {
        type: FIELD_TYPES.ARRAY,
        name: "repositoryNames",
        displayName: "Repository Names",
        description: "List of ECR repository names to create",
        placeholder: "frontend, backend, api",
        defaultValue: [],
        section: FIELD_SECTIONS.BASIC,
        helpText:
          "Enter repository names separated by commas. Each repository will use the global settings below.",
      },
      repositoryType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "repositoryType",
        displayName: "Repository Type",
        description: "Repository visibility (applies to all repositories)",
        defaultValue: "private",
        options: [
          { value: "private", label: "Private - Requires authentication" },
          { value: "public", label: "Public - Accessible without authentication" },
        ],
        section: FIELD_SECTIONS.CONFIGURATION,
        helpText: "Choose whether repositories should be private or public",
      },
      imageTagMutability: {
        type: FIELD_TYPES.DROPDOWN,
        name: "imageTagMutability",
        displayName: "Image Tag Mutability",
        description: "Prevent tag overwrites",
        defaultValue: "IMMUTABLE",
        options: [
          { value: "MUTABLE", label: "Mutable - Tags can be overwritten" },
          { value: "IMMUTABLE", label: "Immutable - Tags cannot be overwritten" },
        ],
        section: FIELD_SECTIONS.CONFIGURATION,
        helpText: "IMMUTABLE prevents accidental tag overwrites and improves security",
      },
      encryptionType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "encryptionType",
        displayName: "Encryption Type",
        description: "Image encryption method",
        defaultValue: "AES256",
        options: [
          { value: "AES256", label: "AES256 - AWS managed encryption" },
          { value: "KMS", label: "KMS - Customer managed keys (additional cost)" },
        ],
        section: FIELD_SECTIONS.SECURITY,
        helpText: "AES256 is free, KMS provides more control but incurs charges",
      },
      enableScanning: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableScanning",
        displayName: "Enable Vulnerability Scanning",
        description: "Automatically scan images for vulnerabilities on push",
        defaultValue: true,
        section: FIELD_SECTIONS.SECURITY,
        helpText: "Recommended for production workloads",
      },
      scanType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "scanType",
        displayName: "Scan Type",
        description: "Level of vulnerability scanning",
        defaultValue: "BASIC",
        options: [
          { value: "BASIC", label: "Basic - Standard CVE scanning (free)" },
          { value: "ENHANCED", label: "Enhanced - AWS Inspector integration (charged)" },
        ],
        section: FIELD_SECTIONS.SECURITY,
        dependsOn: { field: "enableScanning", value: true },
        helpText: "Enhanced scanning provides deeper OS and programming language package scanning",
      },
      createLifecyclePolicy: {
        type: FIELD_TYPES.TOGGLE,
        name: "createLifecyclePolicy",
        displayName: "Enable Lifecycle Policy",
        description: "Automatically cleanup old images to save storage costs",
        defaultValue: true,
        section: FIELD_SECTIONS.LIFECYCLE,
        helpText: "Lifecycle policies help manage storage costs by removing unused images",
      },
      lifecyclePolicyMaxImages: {
        type: FIELD_TYPES.NUMBER,
        name: "lifecyclePolicyMaxImages",
        displayName: "Maximum Images to Keep",
        description: "Number of images to retain per repository",
        defaultValue: 25,
        min: 1,
        max: 1000,
        section: FIELD_SECTIONS.LIFECYCLE,
        dependsOn: { field: "createLifecyclePolicy", value: true },
        helpText: "Older images beyond this count will be automatically deleted",
      },
      enableReplication: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableReplication",
        displayName: "Enable Cross-Region Replication",
        description: "Replicate images to other regions for disaster recovery",
        defaultValue: false,
        section: FIELD_SECTIONS.ADVANCED,
        helpText: "Useful for multi-region deployments and disaster recovery",
      },
      replicationDestinations: {
        type: FIELD_TYPES.ARRAY,
        name: "replicationDestinations",
        displayName: "Replication Destination Regions",
        description: "List of AWS regions to replicate images to",
        placeholder: "us-west-2, eu-west-1",
        defaultValue: [],
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "enableReplication", value: true },
        helpText: "Enter AWS region codes separated by commas (e.g., us-west-2, eu-central-1)",
      },
    },
  },

  s3: {
    name: "s3",
    displayName: "Simple Storage Service (S3)",
    description: "Scalable object storage with 99.999999999% durability",
    provider: "aws",
    category: "Storage",
    icon: "🪣",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable S3",
        description: "Enable S3 buckets",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      bucketNames: {
        type: FIELD_TYPES.ARRAY,
        name: "bucketNames",
        displayName: "Bucket Names",
        description: "List of bucket names to create (one per line)",
        defaultValue: [],
        placeholder: "my-app-data\nmy-app-backups\nmy-app-logs",
        helpText: "Names must be globally unique and DNS-compliant (lowercase, no spaces)",
        section: FIELD_SECTIONS.BASIC,
      },
    },
  },

  lambda: {
    name: "lambda",
    displayName: "AWS Lambda",
    description: "Serverless compute - run code without managing servers",
    provider: "aws",
    category: "Compute",
    icon: "⚡",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Lambda",
        description: "Enable Lambda functions",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      functionNames: {
        type: FIELD_TYPES.ARRAY,
        name: "functionNames",
        displayName: "Function Names",
        description: "List of Lambda function names to create (one per line)",
        defaultValue: [],
        placeholder: "api-handler\ndata-processor\nevent-handler",
        helpText: "⚠️ Requires deployment packages in lambda-packages/{name}.zip directory",
        section: FIELD_SECTIONS.BASIC,
      },
    },
  },

  elasticache: {
    name: "elasticache",
    displayName: "ElastiCache",
    description: "Managed in-memory caching - Redis, Valkey, or Memcached",
    provider: "aws",
    category: "Database",
    icon: "⚡",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable ElastiCache",
        description: "Enable in-memory caching service",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      engine: {
        type: FIELD_TYPES.DROPDOWN,
        name: "engine",
        displayName: "Cache Engine",
        description: "Choose your caching engine",
        defaultValue: "valkey",
        options: [
          { value: "valkey", label: "Valkey - Open-source Redis alternative (recommended)" },
          { value: "redis", label: "Redis - In-memory data store" },
          { value: "memcached", label: "Memcached - Simple key-value cache" },
        ],
        helpText: "Valkey is a Redis-compatible fork with no licensing concerns",
        section: FIELD_SECTIONS.BASIC,
      },
      engineVersion: {
        type: FIELD_TYPES.TEXT,
        name: "engineVersion",
        displayName: "Engine Version",
        description: "Cache engine version",
        defaultValue: "7.2",
        placeholder: "7.2 for Valkey/Redis, 1.6.17 for Memcached",
        helpText: "Latest stable version recommended",
        section: FIELD_SECTIONS.BASIC,
      },
      nodeType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "nodeType",
        displayName: "Node Type",
        description: "Instance type for cache nodes",
        defaultValue: "cache.t4g.small",
        options: [
          { value: "cache.t4g.micro", label: "t4g.micro - 0.5GB (Graviton, cost-effective)" },
          { value: "cache.t4g.small", label: "t4g.small - 1.37GB (Graviton, recommended)" },
          { value: "cache.t4g.medium", label: "t4g.medium - 3.09GB (Graviton)" },
          { value: "cache.t3.micro", label: "t3.micro - 0.5GB (x86)" },
          { value: "cache.t3.small", label: "t3.small - 1.37GB (x86)" },
          { value: "cache.t3.medium", label: "t3.medium - 3.09GB (x86)" },
          { value: "cache.r6g.large", label: "r6g.large - 13.07GB (Memory-optimized Graviton)" },
          { value: "cache.r7g.large", label: "r7g.large - 13.07GB (Latest Graviton)" },
        ],
        helpText: "Graviton instances offer better price/performance",
        section: FIELD_SECTIONS.COMPUTE,
      },
      numCacheNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "numCacheNodes",
        displayName: "Number of Cache Nodes",
        description: "Number of cache nodes in the cluster",
        defaultValue: 1,
        min: 1,
        max: 20,
        helpText: "Use 2+ nodes for high availability",
        section: FIELD_SECTIONS.COMPUTE,
      },
      parameterGroupFamily: {
        type: FIELD_TYPES.DROPDOWN,
        name: "parameterGroupFamily",
        displayName: "Parameter Group Family",
        description: "Must match your engine and version",
        defaultValue: "valkey7",
        options: [
          { value: "valkey7", label: "valkey7" },
          { value: "redis7", label: "redis7" },
          { value: "redis6.x", label: "redis6.x" },
          { value: "memcached1.6", label: "memcached1.6" },
        ],
        section: FIELD_SECTIONS.ADVANCED,
      },
      transitEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "transitEncryption",
        displayName: "Transit Encryption (TLS)",
        description: "Encrypt data in transit",
        defaultValue: true,
        helpText: "Recommended for production",
        section: FIELD_SECTIONS.SECURITY,
      },
      atRestEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "atRestEncryption",
        displayName: "At-Rest Encryption",
        description: "Encrypt data at rest",
        defaultValue: true,
        helpText: "Recommended for compliance",
        section: FIELD_SECTIONS.SECURITY,
      },
      authTokenEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "authTokenEnabled",
        displayName: "Auth Token (Password)",
        description: "Enable authentication token (Redis/Valkey AUTH)",
        defaultValue: true,
        helpText: "Recommended for security",
        section: FIELD_SECTIONS.SECURITY,
      },
      maintenanceWindow: {
        type: FIELD_TYPES.TEXT,
        name: "maintenanceWindow",
        displayName: "Maintenance Window",
        description: "Preferred maintenance window (UTC)",
        defaultValue: "sun:05:00-sun:06:00",
        placeholder: "sun:05:00-sun:06:00",
        helpText: "Format: ddd:hh24:mi-ddd:hh24:mi",
        section: FIELD_SECTIONS.ADVANCED,
      },
      snapshotRetentionLimit: {
        type: FIELD_TYPES.NUMBER,
        name: "snapshotRetentionLimit",
        displayName: "Snapshot Retention Days",
        description: "Number of days to retain automatic snapshots",
        defaultValue: 7,
        min: 0,
        max: 35,
        helpText: "Set to 0 to disable snapshots",
        section: FIELD_SECTIONS.BACKUP,
      },
      snapshotWindow: {
        type: FIELD_TYPES.TEXT,
        name: "snapshotWindow",
        displayName: "Snapshot Window",
        description: "Daily time range for automatic snapshots (UTC)",
        defaultValue: "03:00-05:00",
        placeholder: "03:00-05:00",
        helpText: "Choose a low-traffic period",
        section: FIELD_SECTIONS.BACKUP,
      },
      automaticFailover: {
        type: FIELD_TYPES.TOGGLE,
        name: "automaticFailover",
        displayName: "Automatic Failover",
        description: "Enable automatic failover to replica",
        defaultValue: false,
        helpText: "Requires Multi-AZ and 2+ nodes",
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "multiAz", value: true },
      },
      multiAz: {
        type: FIELD_TYPES.TOGGLE,
        name: "multiAz",
        displayName: "Multi-AZ Deployment",
        description: "Deploy across multiple availability zones",
        defaultValue: false,
        helpText: "Recommended for production high availability",
        section: FIELD_SECTIONS.ADVANCED,
      },
    },
  },

  msk: {
    name: "msk",
    displayName: "Managed Streaming for Apache Kafka (MSK)",
    description: "Fully managed Apache Kafka service for real-time streaming",
    provider: "aws",
    category: "Integration",
    icon: "📊",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable MSK",
        description: "Enable managed Kafka streaming",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      kafkaVersion: {
        type: FIELD_TYPES.DROPDOWN,
        name: "kafkaVersion",
        displayName: "Kafka Version",
        description: "Apache Kafka version",
        defaultValue: "3.5.1",
        options: [
          { value: "3.5.1", label: "3.5.1 (Latest stable)" },
          { value: "3.4.0", label: "3.4.0" },
          { value: "3.3.2", label: "3.3.2" },
          { value: "2.8.1", label: "2.8.1 (Legacy)" },
        ],
        helpText: "Use latest stable version for new clusters",
        section: FIELD_SECTIONS.BASIC,
      },
      numberOfBrokerNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "numberOfBrokerNodes",
        displayName: "Number of Broker Nodes",
        description: "Number of broker nodes across availability zones",
        defaultValue: 2,
        min: 2,
        max: 30,
        helpText: "Minimum 2 for HA, use multiples of AZ count",
        section: FIELD_SECTIONS.COMPUTE,
      },
      brokerNodeInstanceType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "brokerNodeInstanceType",
        displayName: "Broker Instance Type",
        description: "EC2 instance type for each broker",
        defaultValue: "kafka.t3.small",
        options: [
          { value: "kafka.t3.small", label: "kafka.t3.small - 2 vCPU, 2GB (Dev/Test)" },
          { value: "kafka.m5.large", label: "kafka.m5.large - 2 vCPU, 8GB" },
          { value: "kafka.m5.xlarge", label: "kafka.m5.xlarge - 4 vCPU, 16GB" },
          { value: "kafka.m5.2xlarge", label: "kafka.m5.2xlarge - 8 vCPU, 32GB (Production)" },
        ],
        helpText: "Choose based on throughput requirements",
        section: FIELD_SECTIONS.COMPUTE,
      },
    },
  },

  waf: {
    name: "waf",
    displayName: "Web Application Firewall (WAF)",
    description: "Protect web apps from common exploits and attacks",
    provider: "aws",
    category: "Security",
    icon: "🛡️",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable WAF",
        description: "Enable web application firewall protection",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      name: {
        type: FIELD_TYPES.TEXT,
        name: "name",
        displayName: "WAF Name",
        description: "Name for the WAF Web ACL",
        defaultValue: "waf",
        placeholder: "production-waf",
        section: FIELD_SECTIONS.BASIC,
      },
      description: {
        type: FIELD_TYPES.TEXT,
        name: "description",
        displayName: "Description",
        description: "Description of the WAF configuration",
        defaultValue: "Default AWS WAF Managed rule set",
        placeholder: "WAF for production API endpoints",
        section: FIELD_SECTIONS.BASIC,
      },
      scope: {
        type: FIELD_TYPES.DROPDOWN,
        name: "scope",
        displayName: "Scope",
        description: "Where the WAF will be applied",
        defaultValue: "REGIONAL",
        options: [
          { value: "REGIONAL", label: "Regional - ALB, API Gateway, AppSync" },
          { value: "CLOUDFRONT", label: "CloudFront - Global edge locations" },
        ],
        helpText: "Use REGIONAL for regional resources, CLOUDFRONT for global CDN",
        section: FIELD_SECTIONS.BASIC,
      },
      cloudwatchMetricsEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "cloudwatchMetricsEnabled",
        displayName: "CloudWatch Metrics",
        description: "Enable detailed metrics",
        defaultValue: true,
        helpText: "Recommended for monitoring attack patterns",
        section: FIELD_SECTIONS.MONITORING,
      },
      metricName: {
        type: FIELD_TYPES.TEXT,
        name: "metricName",
        displayName: "Metric Name",
        description: "Name for CloudWatch metrics",
        defaultValue: "WAF-metrics",
        placeholder: "production-waf-metrics",
        section: FIELD_SECTIONS.MONITORING,
      },
      sampledRequestsEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "sampledRequestsEnabled",
        displayName: "Sampled Requests",
        description: "Store samples of blocked/allowed requests",
        defaultValue: true,
        helpText: "Useful for troubleshooting false positives",
        section: FIELD_SECTIONS.MONITORING,
      },
    },
  },

  sqs: {
    name: "sqs",
    displayName: "Simple Queue Service (SQS)",
    description: "Managed message queuing for decoupled microservices",
    provider: "aws",
    category: "Integration",
    icon: "📬",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable SQS",
        description: "Enable message queuing",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      queueNames: {
        type: FIELD_TYPES.ARRAY,
        name: "queueNames",
        displayName: "Queue Names",
        description: "Queue names to create",
        defaultValue: [],
        placeholder: "orders-queue\npayments-queue\nnotifications-queue",
        helpText: "One queue name per line",
        section: FIELD_SECTIONS.BASIC,
      },
      fifoQueues: {
        type: FIELD_TYPES.TOGGLE,
        name: "fifoQueues",
        displayName: "FIFO Queues",
        description: "Enable First-In-First-Out ordering",
        defaultValue: false,
        helpText: "FIFO ensures exactly-once processing and strict ordering",
        section: FIELD_SECTIONS.BASIC,
      },
      contentBasedDeduplication: {
        type: FIELD_TYPES.TOGGLE,
        name: "contentBasedDeduplication",
        displayName: "Content-Based Deduplication",
        description: "Auto-deduplicate based on message content",
        defaultValue: false,
        helpText: "Only for FIFO queues",
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "fifoQueues", value: true },
      },
      visibilityTimeout: {
        type: FIELD_TYPES.NUMBER,
        name: "visibilityTimeout",
        displayName: "Visibility Timeout (seconds)",
        description: "How long messages are invisible after being received",
        defaultValue: 30,
        min: 0,
        max: 43200,
        helpText: "Should be longer than your processing time",
        section: FIELD_SECTIONS.ADVANCED,
      },
      messageRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "messageRetention",
        displayName: "Message Retention (seconds)",
        description: "How long to keep messages before deletion",
        defaultValue: 345600,
        min: 60,
        max: 1209600,
        helpText: "Default 4 days, max 14 days",
        section: FIELD_SECTIONS.ADVANCED,
      },
      maxMessageSize: {
        type: FIELD_TYPES.NUMBER,
        name: "maxMessageSize",
        displayName: "Max Message Size (bytes)",
        description: "Maximum size per message",
        defaultValue: 262144,
        min: 1024,
        max: 262144,
        helpText: "Max 256 KB",
        section: FIELD_SECTIONS.ADVANCED,
      },
      delaySeconds: {
        type: FIELD_TYPES.NUMBER,
        name: "delaySeconds",
        displayName: "Delivery Delay (seconds)",
        description: "Delay before messages become available",
        defaultValue: 0,
        min: 0,
        max: 900,
        helpText: "Useful for scheduled processing",
        section: FIELD_SECTIONS.ADVANCED,
      },
      receiveWaitTime: {
        type: FIELD_TYPES.NUMBER,
        name: "receiveWaitTime",
        displayName: "Receive Wait Time (seconds)",
        description: "Long polling wait time",
        defaultValue: 0,
        min: 0,
        max: 20,
        helpText: "Use 1-20 for cost-effective long polling",
        section: FIELD_SECTIONS.ADVANCED,
      },
      createDeadLetterQueue: {
        type: FIELD_TYPES.TOGGLE,
        name: "createDeadLetterQueue",
        displayName: "Dead Letter Queue",
        description: "Capture failed messages for debugging",
        defaultValue: false,
        helpText: "Recommended for production",
        section: FIELD_SECTIONS.ADVANCED,
      },
      maxReceiveCount: {
        type: FIELD_TYPES.NUMBER,
        name: "maxReceiveCount",
        displayName: "Max Receive Count",
        description: "Attempts before moving to DLQ",
        defaultValue: 3,
        min: 1,
        max: 1000,
        helpText: "Typical values: 3-10",
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "createDeadLetterQueue", value: true },
      },
      enableEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableEncryption",
        displayName: "Server-Side Encryption",
        description: "Encrypt messages at rest",
        defaultValue: true,
        helpText: "Recommended for sensitive data",
        section: FIELD_SECTIONS.SECURITY,
      },
    },
  },

  sns: {
    name: "sns",
    displayName: "Simple Notification Service (SNS)",
    description: "Pub/sub messaging for fan-out notifications to subscribers",
    provider: "aws",
    category: "Integration",
    icon: "📢",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable SNS",
        description: "Enable pub/sub notifications",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      topicNames: {
        type: FIELD_TYPES.ARRAY,
        name: "topicNames",
        displayName: "Topic Names",
        description: "SNS topics to create",
        defaultValue: [],
        placeholder: "user-registration\norder-events\nalerts",
        helpText: "One topic name per line",
        section: FIELD_SECTIONS.BASIC,
      },
      fifoTopics: {
        type: FIELD_TYPES.TOGGLE,
        name: "fifoTopics",
        displayName: "FIFO Topics",
        description: "Enable First-In-First-Out ordering",
        defaultValue: false,
        helpText: "FIFO ensures message ordering and deduplication",
        section: FIELD_SECTIONS.BASIC,
      },
      contentBasedDeduplication: {
        type: FIELD_TYPES.TOGGLE,
        name: "contentBasedDeduplication",
        displayName: "Content-Based Deduplication",
        description: "Auto-deduplicate based on message content",
        defaultValue: false,
        helpText: "Only for FIFO topics",
        section: FIELD_SECTIONS.ADVANCED,
        dependsOn: { field: "fifoTopics", value: true },
      },
      enableEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableEncryption",
        displayName: "Enable Encryption",
        description: "Encrypt messages at rest",
        defaultValue: false,
        helpText: "Recommended for sensitive notifications",
        section: FIELD_SECTIONS.SECURITY,
      },
      kmsKeyId: {
        type: FIELD_TYPES.TEXT,
        name: "kmsKeyId",
        displayName: "KMS Key ID",
        description: "KMS key for encryption",
        defaultValue: null,
        placeholder: "arn:aws:kms:region:account:key/...",
        helpText: "Leave empty to use AWS managed key",
        section: FIELD_SECTIONS.SECURITY,
        dependsOn: { field: "enableEncryption", value: true },
      },
    },
  },

  cloudfront: {
    name: "cloudfront",
    displayName: "CloudFront",
    description: "Global CDN for fast content delivery with edge caching",
    provider: "aws",
    category: "Networking",
    icon: "🌍",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable CloudFront",
        description: "Enable global content delivery",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      distributionNames: {
        type: FIELD_TYPES.ARRAY,
        name: "distributionNames",
        displayName: "Distribution Aliases",
        description: "Custom domain names for distributions",
        defaultValue: [],
        placeholder: "cdn.example.com\nstatic.example.com",
        helpText: "Requires ACM certificate in us-east-1",
        section: FIELD_SECTIONS.BASIC,
      },
      priceClass: {
        type: FIELD_TYPES.DROPDOWN,
        name: "priceClass",
        displayName: "Price Class",
        description: "Edge location coverage (affects cost)",
        defaultValue: "PriceClass_100",
        options: [
          { value: "PriceClass_100", label: "US, Canada, Europe (Lowest cost)" },
          { value: "PriceClass_200", label: "+ Asia, Middle East, Africa" },
          { value: "PriceClass_All", label: "All Edge Locations (Global)" },
        ],
        helpText: "Choose based on audience geography",
        section: FIELD_SECTIONS.BASIC,
      },
      enableIpv6: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableIpv6",
        displayName: "Enable IPv6",
        description: "Support IPv6 client connections",
        defaultValue: true,
        helpText: "Recommended for modern apps",
        section: FIELD_SECTIONS.NETWORK,
      },
      enableWaf: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableWaf",
        displayName: "WAF Integration",
        description: "Attach AWS WAF for protection",
        defaultValue: false,
        helpText: "Requires WAF Web ACL with CLOUDFRONT scope",
        section: FIELD_SECTIONS.SECURITY,
      },
      enableLogging: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLogging",
        displayName: "Access Logging",
        description: "Log requests to S3",
        defaultValue: false,
        helpText: "Useful for analytics and debugging",
        section: FIELD_SECTIONS.MONITORING,
      },
      loggingBucket: {
        type: FIELD_TYPES.TEXT,
        name: "loggingBucket",
        displayName: "Logging Bucket",
        description: "S3 bucket for access logs",
        defaultValue: null,
        placeholder: "cloudfront-logs-bucket",
        helpText: "Must be in same account",
        section: FIELD_SECTIONS.MONITORING,
        dependsOn: { field: "enableLogging", value: true },
      },
    },
  },

  route53: {
    name: "route53",
    displayName: "Route 53",
    description: "Scalable DNS and domain management with health checks",
    provider: "aws",
    category: "Networking",
    icon: "🗺️",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Route 53",
        description: "Enable DNS management",
        defaultValue: false,
        section: FIELD_SECTIONS.BASIC,
      },
      zoneNames: {
        type: FIELD_TYPES.ARRAY,
        name: "zoneNames",
        displayName: "Hosted Zone Domains",
        description: "Domain names to manage",
        defaultValue: [],
        placeholder: "example.com\napi.example.com",
        helpText: "Create hosted zones for these domains",
        section: FIELD_SECTIONS.BASIC,
      },
      privateZones: {
        type: FIELD_TYPES.TOGGLE,
        name: "privateZones",
        displayName: "Private Hosted Zones",
        description: "Internal DNS for VPC resources",
        defaultValue: false,
        helpText: "Zones accessible only within VPC",
        section: FIELD_SECTIONS.NETWORK,
      },
      forceDestroy: {
        type: FIELD_TYPES.TOGGLE,
        name: "forceDestroy",
        displayName: "Force Destroy",
        description: "Allow zone deletion with records",
        defaultValue: false,
        helpText: "⚠️ Caution: Enables deletion of non-empty zones",
        section: FIELD_SECTIONS.ADVANCED,
      },
      enableDnssec: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDnssec",
        displayName: "Enable DNSSEC",
        description: "Enable DNS Security Extensions",
        defaultValue: false,
        helpText: "Protects against DNS spoofing",
        section: FIELD_SECTIONS.SECURITY,
      },
    },
  },

  // secretsManager: {
  //   name: "secretsManager",
  //   displayName: "Secrets Manager",
  //   description: "Centralized secrets management",
  //   provider: "aws",
  //   category: "Security",
  //   fields: {
  //     enabled: {
  //       type: FIELD_TYPES.TOGGLE,
  //       name: "enabled",
  //       displayName: "Enable Secrets Manager",
  //       description: "Enable Secrets Manager service",
  //       defaultValue: false,
  //     },
  //     secrets: {
  //       type: FIELD_TYPES.ARRAY,
  //       name: "secrets",
  //       displayName: "Secrets",
  //       description: "Managed secrets",
  //       defaultValue: [],
  //     },
  //     automaticRotation: {
  //       type: FIELD_TYPES.TOGGLE,
  //       name: "automaticRotation",
  //       displayName: "Automatic Rotation",
  //       description: "Enable automatic secret rotation",
  //       defaultValue: false,
  //     },
  //   },
  // },

  // iam: {
  //   name: "iam",
  //   displayName: "Identity and Access Management (IAM)",
  //   description: "Access control and identity management",
  //   provider: "aws",
  //   category: "Security",
  //   fields: {
  //     enabled: {
  //       type: FIELD_TYPES.TOGGLE,
  //       name: "enabled",
  //       displayName: "Enable IAM",
  //       description: "Enable IAM service",
  //       defaultValue: false,
  //     },
  //     roles: {
  //       type: FIELD_TYPES.ARRAY,
  //       name: "roles",
  //       displayName: "Roles",
  //       description: "IAM roles configuration",
  //       defaultValue: [],
  //     },
  //     policies: {
  //       type: FIELD_TYPES.ARRAY,
  //       name: "policies",
  //       displayName: "Policies",
  //       description: "IAM policies configuration",
  //       defaultValue: [],
  //     },
  //     assumeRolePolicyDocument: {
  //       type: FIELD_TYPES.TEXTAREA,
  //       name: "assumeRolePolicyDocument",
  //       displayName: "Assume Role Policy Document",
  //       description: "JSON policy document for role assumption",
  //       defaultValue: null,
  //     },
  //   },
  // },

  // GCP Services
  gke: {
    name: "gke",
    displayName: "Google Kubernetes Engine (GKE)",
    description: "Managed Kubernetes service from Google Cloud",
    provider: "gcp",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable GKE",
        description: "Enable GKE service",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      nodeCount: {
        type: FIELD_TYPES.NUMBER,
        name: "nodeCount",
        displayName: "Node Count",
        description: "Number of nodes",
        defaultValue: 3,
        min: 1,
        max: 100,
      },
      machineType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "machineType",
        displayName: "Machine Type",
        description: "GCE machine type",
        defaultValue: "e2-medium",
        options: [
          { value: "e2-micro", label: "e2-micro" },
          { value: "e2-small", label: "e2-small" },
          { value: "e2-medium", label: "e2-medium" },
          { value: "e2-standard-2", label: "e2-standard-2" },
          { value: "e2-standard-4", label: "e2-standard-4" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "Boot disk size in GB",
        defaultValue: 50,
        min: 20,
        max: 1000,
      },
      enableAutoScaling: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutoScaling",
        displayName: "Auto Scaling",
        description: "Enable node auto scaling",
        defaultValue: true,
      },
      enableAutopilot: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutopilot",
        displayName: "Autopilot Mode",
        description: "Enable GKE Autopilot",
        defaultValue: false,
      },
    },
  },

  cloudSql: {
    name: "cloudSql",
    displayName: "Cloud SQL",
    description: "Managed relational database service",
    provider: "gcp",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Cloud SQL",
        description: "Enable Cloud SQL service",
        defaultValue: false,
      },
      databaseVersion: {
        type: FIELD_TYPES.DROPDOWN,
        name: "databaseVersion",
        displayName: "Database Version",
        description: "Database engine and version",
        defaultValue: "POSTGRES_15",
        options: [
          { value: "POSTGRES_15", label: "PostgreSQL 15" },
          { value: "POSTGRES_14", label: "PostgreSQL 14" },
          { value: "MYSQL_8_0", label: "MySQL 8.0" },
          { value: "MYSQL_5_7", label: "MySQL 5.7" },
        ],
      },
      tier: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tier",
        displayName: "Machine Type",
        description: "Instance tier",
        defaultValue: "db-n1-standard-1",
        options: [
          { value: "db-f1-micro", label: "db-f1-micro" },
          { value: "db-g1-small", label: "db-g1-small" },
          { value: "db-n1-standard-1", label: "db-n1-standard-1" },
          { value: "db-n1-standard-2", label: "db-n1-standard-2" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "Storage size in GB",
        defaultValue: 10,
        min: 10,
        max: 1000,
      },
      enableBackup: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableBackup",
        displayName: "Automated Backup",
        description: "Enable automated backup",
        defaultValue: true,
      },
      enableHighAvailability: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableHighAvailability",
        displayName: "High Availability",
        description: "Enable high availability",
        defaultValue: false,
      },
    },
  },

  // OnPremise Services
  kubernetes: {
    name: "kubernetes",
    displayName: "Kubernetes Cluster",
    description: "Self-managed Kubernetes cluster",
    provider: "onpremise",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Kubernetes",
        description: "Enable Kubernetes cluster",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      masterNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "masterNodes",
        displayName: "Master Nodes",
        description: "Number of master nodes",
        defaultValue: 3,
        min: 1,
        max: 10,
      },
      workerNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "workerNodes",
        displayName: "Worker Nodes",
        description: "Number of worker nodes",
        defaultValue: 3,
        min: 1,
        max: 100,
      },
      networkPlugin: {
        type: FIELD_TYPES.DROPDOWN,
        name: "networkPlugin",
        displayName: "Network Plugin",
        description: "Container network interface",
        defaultValue: "calico",
        options: [
          { value: "calico", label: "Calico" },
          { value: "flannel", label: "Flannel" },
          { value: "weave", label: "Weave Net" },
          { value: "cilium", label: "Cilium" },
        ],
      },
    },
  },

  monitoring: {
    name: "monitoring",
    displayName: "Monitoring Stack",
    description: "Prometheus and Grafana monitoring",
    provider: "onpremise",
    category: "Observability",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Monitoring",
        description: "Enable monitoring stack",
        defaultValue: false,
      },
      enablePrometheus: {
        type: FIELD_TYPES.TOGGLE,
        name: "enablePrometheus",
        displayName: "Prometheus",
        description: "Enable Prometheus metrics collection",
        defaultValue: true,
      },
      enableGrafana: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableGrafana",
        displayName: "Grafana",
        description: "Enable Grafana dashboards",
        defaultValue: true,
      },
      enableAlertmanager: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAlertmanager",
        displayName: "Alertmanager",
        description: "Enable alert management",
        defaultValue: true,
      },
      retentionDays: {
        type: FIELD_TYPES.NUMBER,
        name: "retentionDays",
        displayName: "Retention (days)",
        description: "Metrics retention period",
        defaultValue: 30,
        min: 1,
        max: 365,
      },
    },
  },

  logging: {
    name: "logging",
    displayName: "Logging Stack",
    description: "Centralized logging with ELK stack",
    provider: "onpremise",
    category: "Observability",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Logging",
        description: "Enable logging stack",
        defaultValue: false,
      },
      enableElasticsearch: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableElasticsearch",
        displayName: "Elasticsearch",
        description: "Enable Elasticsearch",
        defaultValue: true,
      },
      enableLogstash: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLogstash",
        displayName: "Logstash",
        description: "Enable Logstash",
        defaultValue: true,
      },
      enableKibana: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableKibana",
        displayName: "Kibana",
        description: "Enable Kibana dashboards",
        defaultValue: true,
      },
      enableFluentd: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableFluentd",
        displayName: "Fluentd",
        description: "Enable Fluentd log collection",
        defaultValue: true,
      },
    },
  },

  storage: {
    name: "storage",
    displayName: "Storage Solutions",
    description: "Persistent storage configuration",
    provider: "onpremise",
    category: "Storage",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Storage",
        description: "Enable storage solutions",
        defaultValue: false,
      },
      enableNFS: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableNFS",
        displayName: "NFS",
        description: "Enable NFS storage",
        defaultValue: false,
      },
      enableCeph: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableCeph",
        displayName: "Ceph",
        description: "Enable Ceph distributed storage",
        defaultValue: false,
      },
      enableLonghorn: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLonghorn",
        displayName: "Longhorn",
        description: "Enable Longhorn cloud-native storage",
        defaultValue: true,
      },
      replicationFactor: {
        type: FIELD_TYPES.NUMBER,
        name: "replicationFactor",
        displayName: "Replication Factor",
        description: "Storage replication factor",
        defaultValue: 3,
        min: 1,
        max: 5,
      },
    },
  },

  networking: {
    name: "networking",
    displayName: "Network Configuration",
    description: "Network infrastructure setup",
    provider: "onpremise",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Networking",
        description: "Enable network configuration",
        defaultValue: false,
      },
      enableLoadBalancer: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLoadBalancer",
        displayName: "Load Balancer",
        description: "Enable load balancer (MetalLB)",
        defaultValue: true,
      },
      enableIngress: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableIngress",
        displayName: "Ingress Controller",
        description: "Enable ingress controller",
        defaultValue: true,
      },
      ingressType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "ingressType",
        displayName: "Ingress Type",
        description: "Ingress controller type",
        defaultValue: "nginx",
        options: [
          { value: "nginx", label: "NGINX" },
          { value: "traefik", label: "Traefik" },
          { value: "haproxy", label: "HAProxy" },
        ],
      },
      enableSSL: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableSSL",
        displayName: "SSL/TLS",
        description: "Enable SSL/TLS certificates",
        defaultValue: true,
      },
    },
  },
};

export const getServiceConfig = (serviceName) => {
  return SERVICES_CONFIG[serviceName];
};

export const getServicesByProvider = (providerType) => {
  return Object.values(SERVICES_CONFIG).filter((service) => service.provider === providerType);
};

export const getServicesByCategory = (category) => {
  return Object.values(SERVICES_CONFIG).filter((service) => service.category === category);
};

export const createDefaultServiceConfig = (serviceName) => {
  const config = getServiceConfig(serviceName);
  if (!config) return {};

  const defaultConfig = {};
  for (const [fieldName, fieldConfig] of Object.entries(config.fields)) {
    defaultConfig[fieldName] = fieldConfig.defaultValue;
  }

  return defaultConfig;
};
