// src/config/servicesConfig.js

export const FIELD_TYPES = {
  TEXT: "text",
  NUMBER: "number",
  TOGGLE: "toggle",
  DROPDOWN: "dropdown",
  MULTISELECT: "multiselect",
  TEXTAREA: "textarea",
  ARRAY: "array",
  OBJECT: "object",
};

export const SERVICES_CONFIG = {
  // AWS Services
  vpc: {
    name: "vpc",
    displayName: "Virtual Private Cloud (VPC)",
    description: "AWS Virtual Private Cloud for network isolation",
    provider: "aws",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable VPC",
        description: "Enable VPC service",
        defaultValue: false,
      },
      cidr: {
        type: FIELD_TYPES.TEXT,
        name: "cidr",
        displayName: "CIDR Block",
        description: "The CIDR block for the VPC",
        defaultValue: "10.0.0.0/16",
        validation: { pattern: /^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/ },
      },
      azCount: {
        type: FIELD_TYPES.DROPDOWN,
        name: "azCount",
        displayName: "Availability Zones",
        description: "Number of availability zones",
        defaultValue: 2,
        options: [
          { value: 1, label: "1" },
          { value: 2, label: "2" },
          { value: 3, label: "3" },
        ],
      },
      createPublicSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createPublicSubnets",
        displayName: "Public Subnets",
        description: "Create public subnets",
        defaultValue: true,
      },
      createPrivateSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createPrivateSubnets",
        displayName: "Private Subnets",
        description: "Create private subnets",
        defaultValue: true,
      },
      createIntraSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createIntraSubnets",
        displayName: "Intra Subnets",
        description: "Create intra subnets (no internet access)",
        defaultValue: false,
      },
      createDatabaseSubnets: {
        type: FIELD_TYPES.TOGGLE,
        name: "createDatabaseSubnets",
        displayName: "Database Subnets",
        description: "Create database subnets",
        defaultValue: false,
      },
      createDatabaseSubnetGroup: {
        type: FIELD_TYPES.TOGGLE,
        name: "createDatabaseSubnetGroup",
        displayName: "DB Subnet Group",
        description: "Create database subnet group",
        defaultValue: true,
      },
      natGateway: {
        type: FIELD_TYPES.DROPDOWN,
        name: "natGateway",
        displayName: "NAT Gateway",
        description: "NAT Gateway configuration",
        defaultValue: "SINGLE",
        options: [
          { value: "NO_NAT", label: "No NAT Gateway" },
          { value: "SINGLE", label: "Single NAT Gateway" },
          { value: "ONE_PER_SUBNET", label: "One per Subnet" },
          { value: "ONE_PER_AZ", label: "One per AZ" },
        ],
      },
      publicSubnetTags: {
        type: FIELD_TYPES.OBJECT,
        name: "publicSubnetTags",
        displayName: "Public Subnet Tags",
        description: "Additional tags for public subnets",
      },
      privateSubnetTags: {
        type: FIELD_TYPES.OBJECT,
        name: "privateSubnetTags",
        displayName: "Private Subnet Tags",
        description: "Additional tags for private subnets",
      },
      databaseSubnetTags: {
        type: FIELD_TYPES.OBJECT,
        name: "databaseSubnetTags",
        displayName: "Database Subnet Tags",
        description: "Additional tags for database subnets",
      },
      enableVpnGateway: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableVpnGateway",
        displayName: "VPN Gateway",
        description: "Enable VPN Gateway",
        defaultValue: false,
      },
      enableFlowLogs: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableFlowLogs",
        displayName: "Flow Logs",
        description: "Enable VPC Flow Logs",
        defaultValue: false,
      },
      enableDnsHostnames: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDnsHostnames",
        displayName: "DNS Hostnames",
        description: "Enable DNS hostnames",
        defaultValue: true,
      },
      enableDnsSupport: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDnsSupport",
        displayName: "DNS Support",
        description: "Enable DNS support",
        defaultValue: true,
      },
    },
  },

  eks: {
    name: "eks",
    displayName: "Elastic Kubernetes Service (EKS)",
    description: "Managed Kubernetes service from AWS",
    provider: "aws",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable EKS",
        description: "Enable EKS service",
        defaultValue: false,
      },
      kubernetesVersion: {
        type: FIELD_TYPES.DROPDOWN,
        name: "kubernetesVersion",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.34",
        options: [
          { value: "1.30", label: "1.30" },
          { value: "1.31", label: "1.31" },
          { value: "1.32", label: "1.32" },
          { value: "1.33", label: "1.33" },
          { value: "1.34", label: "1.34" },
        ],
      },
      enableClusterCreatorAdminPermissions: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableClusterCreatorAdminPermissions",
        displayName: "Cluster Creator Admin",
        description: "Enable cluster creator admin permissions",
        defaultValue: true,
      },
      endpointPublicAccess: {
        type: FIELD_TYPES.TOGGLE,
        name: "endpointPublicAccess",
        displayName: "Public Endpoint",
        description: "Enable public access to cluster endpoint",
        defaultValue: true,
      },
      authenticationMode: {
        type: FIELD_TYPES.DROPDOWN,
        name: "authenticationMode",
        displayName: "Authentication Mode",
        description: "Authentication mode for the cluster",
        defaultValue: "API",
        options: [
          { value: "API", label: "API" },
          { value: "API_AND_CONFIG_MAP", label: "API and ConfigMap" },
          { value: "CONFIG_MAP", label: "ConfigMap" },
        ],
      },
      enableIrsa: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableIrsa",
        displayName: "IRSA",
        description: "Enable IAM Roles for Service Accounts",
        defaultValue: true,
      },
      defaultNodeGroupAmiType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "defaultNodeGroupAmiType",
        displayName: "AMI Type",
        description: "AMI type for node group",
        defaultValue: "BOTTLEROCKET_ARM_64",
        options: [
          { value: "AL2_x86_64", label: "Amazon Linux 2 (x86_64)" },
          { value: "AL2_x86_64_GPU", label: "Amazon Linux 2 GPU (x86_64)" },
          { value: "AL2_ARM_64", label: "Amazon Linux 2 (ARM64)" },
          { value: "BOTTLEROCKET_ARM_64", label: "Bottlerocket (ARM64)" },
          { value: "BOTTLEROCKET_x86_64", label: "Bottlerocket (x86_64)" },
        ],
      },
      defaultNodeGroupInstanceTypes: {
        type: FIELD_TYPES.MULTISELECT,
        name: "defaultNodeGroupInstanceTypes",
        displayName: "Instance Types",
        description: "EC2 instance types",
        defaultValue: ["t4g.large"],
        options: [
          { value: "t3.micro", label: "t3.micro" },
          { value: "t3.small", label: "t3.small" },
          { value: "t3.medium", label: "t3.medium" },
          { value: "t3.large", label: "t3.large" },
          { value: "t4g.medium", label: "t4g.medium" },
          { value: "t4g.large", label: "t4g.large" },
          { value: "m5.large", label: "m5.large" },
          { value: "m5.xlarge", label: "m5.xlarge" },
        ],
      },
      defaultNodeGroupCapacityType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "defaultNodeGroupCapacityType",
        displayName: "Capacity Type",
        description: "Capacity type for node group",
        defaultValue: "ON_DEMAND",
        options: [
          { value: "ON_DEMAND", label: "On-Demand" },
          { value: "SPOT", label: "Spot" },
        ],
      },
      defaultNodeGroupMinSize: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupMinSize",
        displayName: "Min Nodes",
        description: "Minimum number of nodes",
        defaultValue: 1,
        min: 0,
        max: 100,
      },
      defaultNodeGroupMaxSize: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupMaxSize",
        displayName: "Max Nodes",
        description: "Maximum number of nodes",
        defaultValue: 10,
        min: 1,
        max: 100,
      },
      defaultNodeGroupDesiredSize: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupDesiredSize",
        displayName: "Desired Nodes",
        description: "Desired number of nodes",
        defaultValue: 2,
        min: 0,
        max: 100,
      },
      defaultNodeGroupMaxUnavailable: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultNodeGroupMaxUnavailable",
        displayName: "Max Unavailable",
        description: "Max unavailable nodes during updates",
        defaultValue: 1,
        min: 1,
        max: 10,
      },
      addons: {
        type: FIELD_TYPES.OBJECT,
        name: "addons",
        displayName: "EKS Addons",
        description: "EKS managed addons",
      },
      karpenterEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "karpenterEnabled",
        displayName: "Enable Karpenter",
        description: "Enable Karpenter node autoscaler",
        defaultValue: true,
      },
      karpenterNodepoolArch: {
        type: FIELD_TYPES.DROPDOWN,
        name: "karpenterNodepoolArch",
        displayName: "Karpenter Architecture",
        description: "Default Karpenter nodepool architecture",
        defaultValue: "arm64",
        options: [
          { value: "amd64", label: "AMD64 (x86_64)" },
          { value: "arm64", label: "ARM64" },
        ],
      },
      karpenterNodepoolCapacityType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "karpenterNodepoolCapacityType",
        displayName: "Karpenter Capacity Type",
        description: "Default Karpenter capacity type",
        defaultValue: "spot",
        options: [
          { value: "on-demand", label: "On-Demand" },
          { value: "spot", label: "Spot" },
        ],
      },
    },
  },

  rds: {
    name: "rds",
    displayName: "Relational Database Service (RDS)",
    description: "Managed relational database service",
    provider: "aws",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable RDS",
        description: "Enable RDS service",
        defaultValue: false,
      },
      engine: {
        type: FIELD_TYPES.DROPDOWN,
        name: "engine",
        displayName: "Database Engine",
        description: "Database engine type",
        defaultValue: "postgres",
        options: [
          { value: "postgres", label: "PostgreSQL" },
          { value: "mysql", label: "MySQL" },
          { value: "mariadb", label: "MariaDB" },
          { value: "oracle-ee", label: "Oracle" },
          { value: "sqlserver-ex", label: "SQL Server" },
        ],
      },
      version: {
        type: FIELD_TYPES.TEXT,
        name: "version",
        displayName: "Engine Version",
        description: "Database engine version",
        defaultValue: "15.4",
      },
      majorEngineVersion: {
        type: FIELD_TYPES.TEXT,
        name: "majorEngineVersion",
        displayName: "Major Engine Version",
        description:
          "Major database engine version (e.g., 15 for PostgreSQL, 8.0 for MySQL)",
        defaultValue: "15.4",
      },
      family: {
        type: FIELD_TYPES.TEXT,
        name: "family",
        displayName: "DB Parameter Group Family",
        description:
          "Database parameter group family (e.g., postgres15, mysql8.0)",
        defaultValue: "postgres15",
      },
      instanceClass: {
        type: FIELD_TYPES.DROPDOWN,
        name: "instanceClass",
        displayName: "Instance Class",
        description: "RDS instance class",
        defaultValue: "db.t3.small",
        options: [
          { value: "db.t3.micro", label: "db.t3.micro" },
          { value: "db.t3.small", label: "db.t3.small" },
          { value: "db.t3.medium", label: "db.t3.medium" },
          { value: "db.t3.large", label: "db.t3.large" },
          { value: "db.r5.large", label: "db.r5.large" },
          { value: "db.r5.xlarge", label: "db.r5.xlarge" },
        ],
      },
      allocatedStorage: {
        type: FIELD_TYPES.NUMBER,
        name: "allocatedStorage",
        displayName: "Storage (GB)",
        description: "Allocated storage in GB",
        defaultValue: 20,
        min: 20,
        max: 1000,
      },
      maxAllocatedStorage: {
        type: FIELD_TYPES.NUMBER,
        name: "maxAllocatedStorage",
        displayName: "Max Storage (GB)",
        description: "Maximum allocated storage in GB",
        defaultValue: 100,
        min: 20,
        max: 10000,
      },
      multiAz: {
        type: FIELD_TYPES.TOGGLE,
        name: "multiAz",
        displayName: "Multi-AZ",
        description: "Enable Multi-AZ deployment",
        defaultValue: false,
      },
      backupRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "backupRetention",
        displayName: "Backup Retention (days)",
        description: "Backup retention period in days",
        defaultValue: 7,
        min: 0,
        max: 35,
      },
      backupWindow: {
        type: FIELD_TYPES.TEXT,
        name: "backupWindow",
        displayName: "Backup Window",
        description: "Preferred backup window (UTC)",
        defaultValue: "03:00-06:00",
      },
      maintenanceWindow: {
        type: FIELD_TYPES.TEXT,
        name: "maintenanceWindow",
        displayName: "Maintenance Window",
        description: "Preferred maintenance window (UTC)",
        defaultValue: "Mon:00:00-Mon:03:00",
      },
      deletionProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "deletionProtection",
        displayName: "Deletion Protection",
        description: "Enable deletion protection",
        defaultValue: false,
      },
      skipFinalSnapshot: {
        type: FIELD_TYPES.TOGGLE,
        name: "skipFinalSnapshot",
        displayName: "Skip Final Snapshot",
        description: "Skip final snapshot when deleting",
        defaultValue: true,
      },
      applyImmediately: {
        type: FIELD_TYPES.TOGGLE,
        name: "applyImmediately",
        displayName: "Apply Immediately",
        description: "Apply changes immediately",
        defaultValue: false,
      },
      autoMinorVersionUpgrade: {
        type: FIELD_TYPES.TOGGLE,
        name: "autoMinorVersionUpgrade",
        displayName: "Auto Minor Version Upgrade",
        description: "Enable automatic minor version upgrades",
        defaultValue: true,
      },
      publiclyAccessible: {
        type: FIELD_TYPES.TOGGLE,
        name: "publiclyAccessible",
        displayName: "Publicly Accessible",
        description: "Make database publicly accessible",
        defaultValue: false,
      },
      iamDatabaseAuthenticationEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "iamDatabaseAuthenticationEnabled",
        displayName: "IAM Database Authentication",
        description: "Enable IAM database authentication",
        defaultValue: false,
      },
      manageMasterUserPassword: {
        type: FIELD_TYPES.TOGGLE,
        name: "manageMasterUserPassword",
        displayName: "AWS Managed Master Password",
        description: "Let AWS Secrets Manager manage the master password",
        defaultValue: false,
      },
      performanceInsights: {
        type: FIELD_TYPES.TOGGLE,
        name: "performanceInsights",
        displayName: "Performance Insights",
        description: "Enable Performance Insights",
        defaultValue: false,
      },
      performanceInsightsRetentionPeriod: {
        type: FIELD_TYPES.NUMBER,
        name: "performanceInsightsRetentionPeriod",
        displayName: "Performance Insights Retention (days)",
        description: "Performance Insights retention period",
        defaultValue: 7,
        min: 7,
        max: 731,
      },
      monitoringInterval: {
        type: FIELD_TYPES.DROPDOWN,
        name: "monitoringInterval",
        displayName: "Enhanced Monitoring Interval (seconds)",
        description: "Enhanced monitoring interval",
        defaultValue: 0,
        options: [
          { value: 0, label: "Disabled" },
          { value: 1, label: "1 second" },
          { value: 5, label: "5 seconds" },
          { value: 10, label: "10 seconds" },
          { value: 15, label: "15 seconds" },
          { value: 30, label: "30 seconds" },
          { value: 60, label: "60 seconds" },
        ],
      },
      deleteAutomatedBackups: {
        type: FIELD_TYPES.TOGGLE,
        name: "deleteAutomatedBackups",
        displayName: "Delete Automated Backups",
        description: "Delete automated backups on instance deletion",
        defaultValue: true,
      },
    },
  },

  aurora: {
    name: "aurora",
    displayName: "Aurora Serverless",
    description: "Serverless relational database with auto-scaling",
    provider: "aws",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Aurora",
        description: "Enable Aurora Serverless service",
        defaultValue: false,
      },
      engine: {
        type: FIELD_TYPES.DROPDOWN,
        name: "engine",
        displayName: "Database Engine",
        description: "Aurora database engine",
        defaultValue: "aurora-postgresql",
        options: [
          { value: "aurora-postgresql", label: "Aurora PostgreSQL" },
          { value: "aurora-mysql", label: "Aurora MySQL" },
        ],
      },
      engineVersion: {
        type: FIELD_TYPES.TEXT,
        name: "engineVersion",
        displayName: "Engine Version",
        description: "Aurora engine version",
        defaultValue: "15.8",
      },
      instances: {
        type: FIELD_TYPES.OBJECT,
        name: "instances",
        displayName: "Aurora Instances",
        description: "Map of Aurora instances configuration",
        defaultValue: { one: {} },
      },
      serverlessv2MinCapacity: {
        type: FIELD_TYPES.NUMBER,
        name: "serverlessv2MinCapacity",
        displayName: "Min Capacity (ACU)",
        description: "Minimum Aurora Capacity Units",
        defaultValue: 0,
        min: 0,
        max: 128,
      },
      serverlessv2MaxCapacity: {
        type: FIELD_TYPES.NUMBER,
        name: "serverlessv2MaxCapacity",
        displayName: "Max Capacity (ACU)",
        description: "Maximum Aurora Capacity Units",
        defaultValue: 10,
        min: 0.5,
        max: 128,
      },
      serverlessv2SecondsUntilAutoPause: {
        type: FIELD_TYPES.NUMBER,
        name: "serverlessv2SecondsUntilAutoPause",
        displayName: "Seconds Until Auto Pause",
        description: "Seconds until Aurora Serverless auto-pauses",
        defaultValue: 3600,
        min: 300,
        max: 86400,
      },
      backupRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "backupRetention",
        displayName: "Backup Retention (days)",
        description: "Backup retention period in days",
        defaultValue: 7,
        min: 1,
        max: 35,
      },
      deletionProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "deletionProtection",
        displayName: "Deletion Protection",
        description: "Enable deletion protection",
        defaultValue: false,
      },
      enableHttpEndpoint: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableHttpEndpoint",
        displayName: "Data API",
        description: "Enable HTTP endpoint for Data API",
        defaultValue: true,
      },
      iamDatabaseAuthenticationEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "iamDatabaseAuthenticationEnabled",
        displayName: "IAM Database Authentication",
        description: "Enable IAM database authentication",
        defaultValue: true,
      },
      monitoringInterval: {
        type: FIELD_TYPES.DROPDOWN,
        name: "monitoringInterval",
        displayName: "Enhanced Monitoring Interval (seconds)",
        description: "Enhanced monitoring interval",
        defaultValue: 60,
        options: [
          { value: 0, label: "Disabled" },
          { value: 1, label: "1 second" },
          { value: 5, label: "5 seconds" },
          { value: 10, label: "10 seconds" },
          { value: 15, label: "15 seconds" },
          { value: 30, label: "30 seconds" },
          { value: 60, label: "60 seconds" },
        ],
      },
      applyImmediately: {
        type: FIELD_TYPES.TOGGLE,
        name: "applyImmediately",
        displayName: "Apply Immediately",
        description: "Apply changes immediately",
        defaultValue: true,
      },
      skipFinalSnapshot: {
        type: FIELD_TYPES.TOGGLE,
        name: "skipFinalSnapshot",
        displayName: "Skip Final Snapshot",
        description: "Skip final snapshot when deleting",
        defaultValue: true,
      },
      deleteAutomatedBackups: {
        type: FIELD_TYPES.TOGGLE,
        name: "deleteAutomatedBackups",
        displayName: "Delete Automated Backups",
        description: "Delete automated backups on cluster deletion",
        defaultValue: true,
      },
    },
  },

  // Azure Services
  vnet: {
    name: "vnet",
    displayName: "Virtual Network (VNet)",
    description: "Azure Virtual Network for network isolation",
    provider: "azure",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable VNet",
        description: "Enable VNet service",
        defaultValue: false,
      },
      addressSpace: {
        type: FIELD_TYPES.TEXT,
        name: "addressSpace",
        displayName: "Address Space",
        description: "The address space for the VNet",
        defaultValue: "10.0.0.0/16",
        validation: { pattern: /^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/ },
      },
      subnets: {
        type: FIELD_TYPES.OBJECT,
        name: "subnets",
        displayName: "Subnets",
        description: "Subnet configurations",
      },
      enableDdosProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDdosProtection",
        displayName: "DDoS Protection",
        description: "Enable DDoS protection",
        defaultValue: false,
      },
      enableVmProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableVmProtection",
        displayName: "VM Protection",
        description: "Enable VM protection",
        defaultValue: false,
      },
    },
  },

  aks: {
    name: "aks",
    displayName: "Azure Kubernetes Service (AKS)",
    description: "Managed Kubernetes service from Azure",
    provider: "azure",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable AKS",
        description: "Enable AKS service",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      nodeGroups: {
        type: FIELD_TYPES.NUMBER,
        name: "nodeGroups",
        displayName: "Node Pools",
        description: "Number of node pools",
        defaultValue: 1,
        min: 1,
        max: 10,
      },
      minNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "minNodes",
        displayName: "Min Nodes",
        description: "Minimum number of nodes",
        defaultValue: 2,
        min: 1,
        max: 100,
      },
      maxNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "maxNodes",
        displayName: "Max Nodes",
        description: "Maximum number of nodes",
        defaultValue: 5,
        min: 1,
        max: 100,
      },
      vmSize: {
        type: FIELD_TYPES.DROPDOWN,
        name: "vmSize",
        displayName: "VM Size",
        description: "Azure VM size",
        defaultValue: "Standard_D2s_v3",
        options: [
          { value: "Standard_B2s", label: "Standard_B2s" },
          { value: "Standard_D2s_v3", label: "Standard_D2s_v3" },
          { value: "Standard_D4s_v3", label: "Standard_D4s_v3" },
          { value: "Standard_D8s_v3", label: "Standard_D8s_v3" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "OS disk size in GB",
        defaultValue: 50,
        min: 30,
        max: 1000,
      },
      enableAutoScaling: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutoScaling",
        displayName: "Auto Scaling",
        description: "Enable node auto scaling",
        defaultValue: true,
      },
      enableClusterAutoscaler: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableClusterAutoscaler",
        displayName: "Cluster Autoscaler",
        description: "Enable cluster autoscaler",
        defaultValue: false,
      },
      enableMetricsServer: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableMetricsServer",
        displayName: "Metrics Server",
        description: "Enable metrics server",
        defaultValue: true,
      },
      addons: {
        type: FIELD_TYPES.OBJECT,
        name: "addons",
        displayName: "AKS Addons",
        description: "AKS managed addons",
      },
    },
  },

  sqlDatabase: {
    name: "sqlDatabase",
    displayName: "Azure SQL Database",
    description: "Managed SQL database service",
    provider: "azure",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable SQL Database",
        description: "Enable Azure SQL Database",
        defaultValue: false,
      },
      tier: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tier",
        displayName: "Service Tier",
        description: "Database service tier",
        defaultValue: "Basic",
        options: [
          { value: "Basic", label: "Basic" },
          { value: "Standard", label: "Standard" },
          { value: "Premium", label: "Premium" },
          { value: "GeneralPurpose", label: "General Purpose" },
          { value: "BusinessCritical", label: "Business Critical" },
        ],
      },
      size: {
        type: FIELD_TYPES.TEXT,
        name: "size",
        displayName: "Compute Size",
        description: "Database compute size",
        defaultValue: "S0",
      },
      maxStorage: {
        type: FIELD_TYPES.NUMBER,
        name: "maxStorage",
        displayName: "Max Storage (GB)",
        description: "Maximum storage in GB",
        defaultValue: 2,
        min: 1,
        max: 1000,
      },
      enableBackup: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableBackup",
        displayName: "Automated Backup",
        description: "Enable automated backup",
        defaultValue: true,
      },
      backupRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "backupRetention",
        displayName: "Backup Retention (days)",
        description: "Backup retention period in days",
        defaultValue: 7,
        min: 1,
        max: 35,
      },
      enableEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableEncryption",
        displayName: "Encryption",
        description: "Enable encryption at rest",
        defaultValue: true,
      },
      enableAdvancedThreatProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAdvancedThreatProtection",
        displayName: "Advanced Threat Protection",
        description: "Enable advanced threat protection",
        defaultValue: false,
      },
      enableAudit: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAudit",
        displayName: "Auditing",
        description: "Enable database auditing",
        defaultValue: false,
      },
    },
  },

  // More AWS Services
  opensearch: {
    name: "opensearch",
    displayName: "OpenSearch Service",
    description: "Managed search and analytics service",
    provider: "aws",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable OpenSearch",
        description: "Enable OpenSearch service",
        defaultValue: false,
      },
      domainName: {
        type: FIELD_TYPES.TEXT,
        name: "domainName",
        displayName: "Domain Name",
        description: "OpenSearch domain name",
        defaultValue: "opensearch",
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "OpenSearch Version",
        description: "OpenSearch version",
        defaultValue: "OpenSearch_2.19",
        options: [
          { value: "OpenSearch_2.19", label: "OpenSearch 2.19" },
          { value: "OpenSearch_2.11", label: "OpenSearch 2.11" },
          { value: "OpenSearch_2.9", label: "OpenSearch 2.9" },
          { value: "OpenSearch_1.3", label: "OpenSearch 1.3" },
        ],
      },
      instanceType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "instanceType",
        displayName: "Instance Type",
        description: "OpenSearch instance type",
        defaultValue: "m7g.medium.search",
        options: [
          { value: "t3.small.search", label: "t3.small.search" },
          { value: "t3.medium.search", label: "t3.medium.search" },
          { value: "m5.large.search", label: "m5.large.search" },
          { value: "m7g.medium.search", label: "m7g.medium.search" },
          { value: "m7g.large.search", label: "m7g.large.search" },
        ],
      },
      instanceCount: {
        type: FIELD_TYPES.NUMBER,
        name: "instanceCount",
        displayName: "Instance Count",
        description: "Number of data instances",
        defaultValue: 3,
        min: 1,
        max: 20,
      },
      dedicatedMasterEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "dedicatedMasterEnabled",
        displayName: "Dedicated Master",
        description: "Enable dedicated master nodes",
        defaultValue: false,
      },
      dedicatedMasterType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "dedicatedMasterType",
        displayName: "Master Instance Type",
        description: "Master node instance type",
        defaultValue: "t3.small.search",
        options: [
          { value: "t3.small.search", label: "t3.small.search" },
          { value: "t3.medium.search", label: "t3.medium.search" },
          { value: "m5.large.search", label: "m5.large.search" },
        ],
      },
      dedicatedMasterCount: {
        type: FIELD_TYPES.NUMBER,
        name: "dedicatedMasterCount",
        displayName: "Master Node Count",
        description: "Number of master nodes",
        defaultValue: 0,
        min: 0,
        max: 5,
      },
      ebsEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "ebsEnabled",
        displayName: "EBS Storage",
        description: "Enable EBS storage volumes",
        defaultValue: true,
      },
      ebsVolumeSize: {
        type: FIELD_TYPES.NUMBER,
        name: "ebsVolumeSize",
        displayName: "EBS Volume Size (GB)",
        description: "EBS volume size per instance",
        defaultValue: 64,
        min: 10,
        max: 1000,
      },
      ebsVolumeType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "ebsVolumeType",
        displayName: "EBS Volume Type",
        description: "EBS volume type",
        defaultValue: "gp3",
        options: [
          { value: "gp3", label: "gp3" },
          { value: "gp2", label: "gp2" },
          { value: "io1", label: "io1" },
        ],
      },
      customEndpointEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "customEndpointEnabled",
        displayName: "Custom Endpoint",
        description: "Enable custom endpoint",
        defaultValue: false,
      },
      nodeToNodeEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "nodeToNodeEncryption",
        displayName: "Node-to-Node Encryption",
        description: "Enable node-to-node encryption",
        defaultValue: true,
      },
      enforceHttps: {
        type: FIELD_TYPES.TOGGLE,
        name: "enforceHttps",
        displayName: "Enforce HTTPS",
        description: "Enforce HTTPS for all traffic",
        defaultValue: true,
      },
      tlsSecurityPolicy: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tlsSecurityPolicy",
        displayName: "TLS Security Policy",
        description: "TLS security policy",
        defaultValue: "Policy-Min-TLS-1-2-2019-07",
        options: [
          { value: "Policy-Min-TLS-1-0-2019-07", label: "TLS 1.0 (Minimum)" },
          { value: "Policy-Min-TLS-1-2-2019-07", label: "TLS 1.2 (Minimum)" },
          { value: "Policy-Min-TLS-1-2-PFS-2023-10", label: "TLS 1.2 PFS" },
        ],
      },
      advancedSecurityEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "advancedSecurityEnabled",
        displayName: "Advanced Security",
        description: "Enable advanced security options",
        defaultValue: true,
      },
      internalUserDatabaseEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "internalUserDatabaseEnabled",
        displayName: "Internal User Database",
        description: "Enable internal user database",
        defaultValue: true,
      },
      masterUserName: {
        type: FIELD_TYPES.TEXT,
        name: "masterUserName",
        displayName: "Master User Name",
        description: "Master user name for authentication",
        defaultValue: "admin",
      },
      createAccessPolicy: {
        type: FIELD_TYPES.TOGGLE,
        name: "createAccessPolicy",
        displayName: "Create Access Policy",
        description: "Create domain access policy",
        defaultValue: true,
      },
      ipAddressType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "ipAddressType",
        displayName: "IP Address Type",
        description: "IP address type for the domain",
        defaultValue: "dualstack",
        options: [
          { value: "ipv4", label: "IPv4 only" },
          { value: "dualstack", label: "IPv4 and IPv6 (Dual Stack)" },
        ],
      },
      allowExplicitIndex: {
        type: FIELD_TYPES.TOGGLE,
        name: "allowExplicitIndex",
        displayName: "Allow Explicit Index",
        description: "Allow explicit index in multi-action requests",
        defaultValue: true,
      },
    },
  },

  ecr: {
    name: "ecr",
    displayName: "Elastic Container Registry (ECR)",
    description:
      "Managed Docker container registry - supports multiple repositories",
    provider: "aws",
    category: "Storage",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable ECR",
        description: "Enable ECR service",
        defaultValue: false,
      },
      repositories: {
        type: FIELD_TYPES.ARRAY,
        name: "repositories",
        displayName: "Repositories",
        description:
          "List of ECR repository names to create (e.g., ['frontend', 'backend', 'api'])",
        defaultValue: [],
      },
      repositoryType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "repositoryType",
        displayName: "Repository Type",
        description: "Repository type (applies to all repositories)",
        defaultValue: "private",
        options: [
          { value: "private", label: "Private" },
          { value: "public", label: "Public" },
        ],
      },
      imageTagMutability: {
        type: FIELD_TYPES.DROPDOWN,
        name: "imageTagMutability",
        displayName: "Image Tag Mutability",
        description: "Prevent image tags from being overwritten",
        defaultValue: "IMMUTABLE",
        options: [
          { value: "MUTABLE", label: "Mutable" },
          { value: "IMMUTABLE", label: "Immutable" },
        ],
      },
      repositoryEncryptionType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "repositoryEncryptionType",
        displayName: "Encryption Type",
        description: "Repository encryption type",
        defaultValue: "AES256",
        options: [
          { value: "AES256", label: "AES256 (Server-side)" },
          { value: "KMS", label: "KMS (Customer Managed Keys)" },
        ],
      },
      repositoryReadWriteAccessArns: {
        type: FIELD_TYPES.ARRAY,
        name: "repositoryReadWriteAccessArns",
        displayName: "Read/Write Access ARNs",
        description: "List of IAM ARNs for read/write access to repositories",
        defaultValue: [],
      },
      createLifecyclePolicy: {
        type: FIELD_TYPES.TOGGLE,
        name: "createLifecyclePolicy",
        displayName: "Create Lifecycle Policy",
        description: "Automatically clean up old images based on rules",
        defaultValue: true,
      },
      lifecyclePolicyRulePriority: {
        type: FIELD_TYPES.NUMBER,
        name: "lifecyclePolicyRulePriority",
        displayName: "Lifecycle Policy Priority",
        description: "Lifecycle policy rule priority",
        defaultValue: 1,
        min: 1,
        max: 999,
      },
      lifecyclePolicyDescription: {
        type: FIELD_TYPES.TEXT,
        name: "lifecyclePolicyDescription",
        displayName: "Lifecycle Policy Description",
        description: "Description for lifecycle policy",
        defaultValue: "Keep last 25 images",
      },
      lifecyclePolicyTagStatus: {
        type: FIELD_TYPES.DROPDOWN,
        name: "lifecyclePolicyTagStatus",
        displayName: "Lifecycle Tag Status",
        description: "Which images to apply policy to",
        defaultValue: "tagged",
        options: [
          { value: "tagged", label: "Tagged" },
          { value: "untagged", label: "Untagged" },
          { value: "any", label: "Any" },
        ],
      },
      lifecyclePolicyTagPrefixList: {
        type: FIELD_TYPES.ARRAY,
        name: "lifecyclePolicyTagPrefixList",
        displayName: "Lifecycle Tag Prefix List",
        description: "Tag prefixes to match (e.g., ['v', 'release'])",
        defaultValue: ["v"],
      },
      lifecyclePolicyCountType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "lifecyclePolicyCountType",
        displayName: "Lifecycle Count Type",
        description: "Count type for lifecycle policy",
        defaultValue: "imageCountMoreThan",
        options: [
          { value: "imageCountMoreThan", label: "Image Count More Than" },
          { value: "sinceImagePushed", label: "Since Image Pushed" },
        ],
      },
      lifecyclePolicyCountNumber: {
        type: FIELD_TYPES.NUMBER,
        name: "lifecyclePolicyCountNumber",
        displayName: "Lifecycle Count Number",
        description: "Number of images to keep or days since pushed",
        defaultValue: 25,
        min: 1,
        max: 1000,
      },
      lifecyclePolicyActionType: {
        type: FIELD_TYPES.TEXT,
        name: "lifecyclePolicyActionType",
        displayName: "Lifecycle Action Type",
        description: "Action to take on matched images",
        defaultValue: "expire",
      },
      enableScanning: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableScanning",
        displayName: "Image Scanning",
        description: "Enable vulnerability scanning on image push",
        defaultValue: true,
      },
      scanType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "scanType",
        displayName: "Scan Type",
        description: "Vulnerability scan type",
        defaultValue: "BASIC",
        options: [
          { value: "BASIC", label: "Basic" },
          { value: "ENHANCED", label: "Enhanced (ECR Enhanced Scanning)" },
        ],
      },
      enableReplication: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableReplication",
        displayName: "Cross-Region Replication",
        description: "Enable automatic replication to other regions",
        defaultValue: false,
      },
      replicationDestinations: {
        type: FIELD_TYPES.ARRAY,
        name: "replicationDestinations",
        displayName: "Replication Destinations",
        description:
          "List of AWS region codes for replication (e.g., ['us-west-2', 'eu-central-1'])",
        defaultValue: [],
      },
    },
  },

  s3: {
    name: "s3",
    displayName: "Simple Storage Service (S3)",
    description: "Scalable object storage service - supports multiple buckets",
    provider: "aws",
    category: "Storage",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable S3",
        description: "Enable S3 service",
        defaultValue: false,
      },
      buckets: {
        type: FIELD_TYPES.ARRAY,
        name: "buckets",
        displayName: "Buckets",
        description:
          "List of S3 buckets to create (array of bucket objects with name and configuration)",
        defaultValue: [],
      },
    },
  },

  lambda: {
    name: "lambda",
    displayName: "AWS Lambda",
    description: "Serverless compute service",
    provider: "aws",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Lambda",
        description: "Enable Lambda service",
        defaultValue: false,
      },
      functions: {
        type: FIELD_TYPES.ARRAY,
        name: "functions",
        displayName: "Functions",
        description: "Lambda functions",
        defaultValue: [],
      },
      defaultRuntime: {
        type: FIELD_TYPES.DROPDOWN,
        name: "defaultRuntime",
        displayName: "Default Runtime",
        description: "Default runtime for new functions",
        defaultValue: "nodejs18.x",
        options: [
          { value: "nodejs18.x", label: "Node.js 18.x" },
          { value: "python3.11", label: "Python 3.11" },
          { value: "java17", label: "Java 17" },
          { value: "dotnet6", label: ".NET 6" },
          { value: "go1.x", label: "Go 1.x" },
        ],
      },
      defaultMemory: {
        type: FIELD_TYPES.DROPDOWN,
        name: "defaultMemory",
        displayName: "Default Memory (MB)",
        description: "Default memory allocation",
        defaultValue: 256,
        options: [
          { value: 128, label: "128 MB" },
          { value: 256, label: "256 MB" },
          { value: 512, label: "512 MB" },
          { value: 1024, label: "1024 MB" },
          { value: 2048, label: "2048 MB" },
          { value: 3008, label: "3008 MB" },
        ],
      },
      defaultTimeout: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultTimeout",
        displayName: "Default Timeout (seconds)",
        description: "Default function timeout",
        defaultValue: 30,
        min: 1,
        max: 900,
      },
    },
  },

  elasticache: {
    name: "elasticache",
    displayName: "ElastiCache",
    description: "In-memory caching service",
    provider: "aws",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable ElastiCache",
        description: "Enable ElastiCache service",
        defaultValue: false,
      },
      engine: {
        type: FIELD_TYPES.DROPDOWN,
        name: "engine",
        displayName: "Cache Engine",
        description: "Cache engine type",
        defaultValue: "redis",
        options: [
          { value: "redis", label: "Redis" },
          { value: "memcached", label: "Memcached" },
        ],
      },
      version: {
        type: FIELD_TYPES.TEXT,
        name: "version",
        displayName: "Engine Version",
        description: "Cache engine version",
        defaultValue: "7.0",
      },
      nodeType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "nodeType",
        displayName: "Node Type",
        description: "Cache node instance type",
        defaultValue: "cache.t3.micro",
        options: [
          { value: "cache.t3.micro", label: "cache.t3.micro" },
          { value: "cache.t3.small", label: "cache.t3.small" },
          { value: "cache.t3.medium", label: "cache.t3.medium" },
          { value: "cache.r6g.large", label: "cache.r6g.large" },
        ],
      },
      numCacheNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "numCacheNodes",
        displayName: "Number of Nodes",
        description: "Number of cache nodes",
        defaultValue: 1,
        min: 1,
        max: 20,
      },
      automaticFailover: {
        type: FIELD_TYPES.TOGGLE,
        name: "automaticFailover",
        displayName: "Automatic Failover",
        description: "Enable automatic failover",
        defaultValue: false,
      },
      multiAz: {
        type: FIELD_TYPES.TOGGLE,
        name: "multiAz",
        displayName: "Multi-AZ",
        description: "Enable Multi-AZ deployment",
        defaultValue: false,
      },
    },
  },

  msk: {
    name: "msk",
    displayName: "Managed Streaming for Apache Kafka (MSK)",
    description: "Fully managed Apache Kafka service",
    provider: "aws",
    category: "Integration",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable MSK",
        description: "Enable MSK service",
        defaultValue: false,
      },
      kafkaVersion: {
        type: FIELD_TYPES.DROPDOWN,
        name: "kafkaVersion",
        displayName: "Kafka Version",
        description: "Apache Kafka version",
        defaultValue: "3.5.1",
        options: [
          { value: "3.5.1", label: "3.5.1" },
          { value: "3.4.0", label: "3.4.0" },
          { value: "3.3.2", label: "3.3.2" },
          { value: "2.8.1", label: "2.8.1" },
        ],
      },
      numberOfBrokerNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "numberOfBrokerNodes",
        displayName: "Number of Broker Nodes",
        description: "Number of broker nodes in the cluster",
        defaultValue: 2,
        min: 2,
        max: 30,
      },
      brokerNodeInstanceType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "brokerNodeInstanceType",
        displayName: "Broker Instance Type",
        description: "EC2 instance type for broker nodes",
        defaultValue: "kafka.t3.small",
        options: [
          { value: "kafka.t3.small", label: "kafka.t3.small" },
          { value: "kafka.m5.large", label: "kafka.m5.large" },
          { value: "kafka.m5.xlarge", label: "kafka.m5.xlarge" },
          { value: "kafka.m5.2xlarge", label: "kafka.m5.2xlarge" },
        ],
      },
    },
  },

  waf: {
    name: "waf",
    displayName: "Web Application Firewall (WAF)",
    description: "AWS WAF web application firewall",
    provider: "aws",
    category: "Security",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable WAF",
        description: "Enable WAF service",
        defaultValue: false,
      },
      name: {
        type: FIELD_TYPES.TEXT,
        name: "name",
        displayName: "WAF Name",
        description: "Name of the WAF Web ACL",
        defaultValue: "waf",
      },
      description: {
        type: FIELD_TYPES.TEXT,
        name: "description",
        displayName: "Description",
        description: "WAF Web ACL description",
        defaultValue: "Default AWS WAF Managed rule set",
      },
      scope: {
        type: FIELD_TYPES.DROPDOWN,
        name: "scope",
        displayName: "Scope",
        description:
          "WAF scope (REGIONAL for ALB/API Gateway, CLOUDFRONT for CloudFront)",
        defaultValue: "REGIONAL",
        options: [
          { value: "REGIONAL", label: "Regional (ALB, API Gateway)" },
          { value: "CLOUDFRONT", label: "CloudFront" },
        ],
      },
      cloudwatchMetricsEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "cloudwatchMetricsEnabled",
        displayName: "CloudWatch Metrics",
        description: "Enable CloudWatch metrics",
        defaultValue: true,
      },
      metricName: {
        type: FIELD_TYPES.TEXT,
        name: "metricName",
        displayName: "Metric Name",
        description: "CloudWatch metric name",
        defaultValue: "WAF-metrics",
      },
      sampledRequestsEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "sampledRequestsEnabled",
        displayName: "Sampled Requests",
        description: "Enable sampled requests",
        defaultValue: true,
      },
    },
  },

  sqs: {
    name: "sqs",
    displayName: "Simple Queue Service (SQS)",
    description: "Managed message queuing service",
    provider: "aws",
    category: "Integration",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable SQS",
        description: "Enable SQS service",
        defaultValue: false,
      },
      queues: {
        type: FIELD_TYPES.ARRAY,
        name: "queues",
        displayName: "Queues",
        description: "SQS queues configuration",
        defaultValue: [],
      },
      defaultVisibilityTimeout: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultVisibilityTimeout",
        displayName: "Default Visibility Timeout (seconds)",
        description: "Default message visibility timeout",
        defaultValue: 30,
        min: 0,
        max: 43200,
      },
      defaultMessageRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "defaultMessageRetention",
        displayName: "Default Message Retention (seconds)",
        description: "Default message retention period",
        defaultValue: 345600,
        min: 60,
        max: 1209600,
      },
    },
  },

  sns: {
    name: "sns",
    displayName: "Simple Notification Service (SNS)",
    description: "Managed pub/sub messaging service",
    provider: "aws",
    category: "Integration",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable SNS",
        description: "Enable SNS service",
        defaultValue: false,
      },
      topics: {
        type: FIELD_TYPES.ARRAY,
        name: "topics",
        displayName: "Topics",
        description: "SNS topics configuration",
        defaultValue: [],
      },
      defaultKmsKeyId: {
        type: FIELD_TYPES.TEXT,
        name: "defaultKmsKeyId",
        displayName: "Default KMS Key ID",
        description: "Default KMS key for encryption",
        defaultValue: null,
      },
    },
  },

  cloudfront: {
    name: "cloudfront",
    displayName: "CloudFront",
    description: "Content delivery network (CDN)",
    provider: "aws",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable CloudFront",
        description: "Enable CloudFront service",
        defaultValue: false,
      },
      distributions: {
        type: FIELD_TYPES.ARRAY,
        name: "distributions",
        displayName: "Distributions",
        description: "CloudFront distributions",
        defaultValue: [],
      },
      priceClass: {
        type: FIELD_TYPES.DROPDOWN,
        name: "priceClass",
        displayName: "Price Class",
        description: "CloudFront price class",
        defaultValue: "PriceClass_100",
        options: [
          { value: "PriceClass_100", label: "Use Only US, Canada and Europe" },
          {
            value: "PriceClass_200",
            label: "Use US, Canada, Europe, Asia, Middle East and Africa",
          },
          { value: "PriceClass_All", label: "Use All Edge Locations" },
        ],
      },
      wafEnabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "wafEnabled",
        displayName: "WAF Integration",
        description: "Enable AWS WAF integration",
        defaultValue: false,
      },
    },
  },

  route53: {
    name: "route53",
    displayName: "Route 53",
    description: "Scalable DNS and domain name system",
    provider: "aws",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Route 53",
        description: "Enable Route 53 service",
        defaultValue: false,
      },
      hostedZones: {
        type: FIELD_TYPES.ARRAY,
        name: "hostedZones",
        displayName: "Hosted Zones",
        description: "DNS hosted zones",
        defaultValue: [],
      },
      recordSets: {
        type: FIELD_TYPES.ARRAY,
        name: "recordSets",
        displayName: "Record Sets",
        description: "DNS record sets",
        defaultValue: [],
      },
    },
  },

  // secretsManager: {
  //   name: "secretsManager",
  //   displayName: "Secrets Manager",
  //   description: "Centralized secrets management",
  //   provider: "aws",
  //   category: "Security",
  //   fields: {
  //     enabled: {
  //       type: FIELD_TYPES.TOGGLE,
  //       name: "enabled",
  //       displayName: "Enable Secrets Manager",
  //       description: "Enable Secrets Manager service",
  //       defaultValue: false,
  //     },
  //     secrets: {
  //       type: FIELD_TYPES.ARRAY,
  //       name: "secrets",
  //       displayName: "Secrets",
  //       description: "Managed secrets",
  //       defaultValue: [],
  //     },
  //     automaticRotation: {
  //       type: FIELD_TYPES.TOGGLE,
  //       name: "automaticRotation",
  //       displayName: "Automatic Rotation",
  //       description: "Enable automatic secret rotation",
  //       defaultValue: false,
  //     },
  //   },
  // },

  // iam: {
  //   name: "iam",
  //   displayName: "Identity and Access Management (IAM)",
  //   description: "Access control and identity management",
  //   provider: "aws",
  //   category: "Security",
  //   fields: {
  //     enabled: {
  //       type: FIELD_TYPES.TOGGLE,
  //       name: "enabled",
  //       displayName: "Enable IAM",
  //       description: "Enable IAM service",
  //       defaultValue: false,
  //     },
  //     roles: {
  //       type: FIELD_TYPES.ARRAY,
  //       name: "roles",
  //       displayName: "Roles",
  //       description: "IAM roles configuration",
  //       defaultValue: [],
  //     },
  //     policies: {
  //       type: FIELD_TYPES.ARRAY,
  //       name: "policies",
  //       displayName: "Policies",
  //       description: "IAM policies configuration",
  //       defaultValue: [],
  //     },
  //     assumeRolePolicyDocument: {
  //       type: FIELD_TYPES.TEXTAREA,
  //       name: "assumeRolePolicyDocument",
  //       displayName: "Assume Role Policy Document",
  //       description: "JSON policy document for role assumption",
  //       defaultValue: null,
  //     },
  //   },
  // },

  // GCP Services
  gke: {
    name: "gke",
    displayName: "Google Kubernetes Engine (GKE)",
    description: "Managed Kubernetes service from Google Cloud",
    provider: "gcp",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable GKE",
        description: "Enable GKE service",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      nodeCount: {
        type: FIELD_TYPES.NUMBER,
        name: "nodeCount",
        displayName: "Node Count",
        description: "Number of nodes",
        defaultValue: 3,
        min: 1,
        max: 100,
      },
      machineType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "machineType",
        displayName: "Machine Type",
        description: "GCE machine type",
        defaultValue: "e2-medium",
        options: [
          { value: "e2-micro", label: "e2-micro" },
          { value: "e2-small", label: "e2-small" },
          { value: "e2-medium", label: "e2-medium" },
          { value: "e2-standard-2", label: "e2-standard-2" },
          { value: "e2-standard-4", label: "e2-standard-4" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "Boot disk size in GB",
        defaultValue: 50,
        min: 20,
        max: 1000,
      },
      enableAutoScaling: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutoScaling",
        displayName: "Auto Scaling",
        description: "Enable node auto scaling",
        defaultValue: true,
      },
      enableAutopilot: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutopilot",
        displayName: "Autopilot Mode",
        description: "Enable GKE Autopilot",
        defaultValue: false,
      },
    },
  },

  cloudSql: {
    name: "cloudSql",
    displayName: "Cloud SQL",
    description: "Managed relational database service",
    provider: "gcp",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Cloud SQL",
        description: "Enable Cloud SQL service",
        defaultValue: false,
      },
      databaseVersion: {
        type: FIELD_TYPES.DROPDOWN,
        name: "databaseVersion",
        displayName: "Database Version",
        description: "Database engine and version",
        defaultValue: "POSTGRES_15",
        options: [
          { value: "POSTGRES_15", label: "PostgreSQL 15" },
          { value: "POSTGRES_14", label: "PostgreSQL 14" },
          { value: "MYSQL_8_0", label: "MySQL 8.0" },
          { value: "MYSQL_5_7", label: "MySQL 5.7" },
        ],
      },
      tier: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tier",
        displayName: "Machine Type",
        description: "Instance tier",
        defaultValue: "db-n1-standard-1",
        options: [
          { value: "db-f1-micro", label: "db-f1-micro" },
          { value: "db-g1-small", label: "db-g1-small" },
          { value: "db-n1-standard-1", label: "db-n1-standard-1" },
          { value: "db-n1-standard-2", label: "db-n1-standard-2" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "Storage size in GB",
        defaultValue: 10,
        min: 10,
        max: 1000,
      },
      enableBackup: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableBackup",
        displayName: "Automated Backup",
        description: "Enable automated backup",
        defaultValue: true,
      },
      enableHighAvailability: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableHighAvailability",
        displayName: "High Availability",
        description: "Enable high availability",
        defaultValue: false,
      },
    },
  },

  // OnPremise Services
  kubernetes: {
    name: "kubernetes",
    displayName: "Kubernetes Cluster",
    description: "Self-managed Kubernetes cluster",
    provider: "onpremise",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Kubernetes",
        description: "Enable Kubernetes cluster",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      masterNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "masterNodes",
        displayName: "Master Nodes",
        description: "Number of master nodes",
        defaultValue: 3,
        min: 1,
        max: 10,
      },
      workerNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "workerNodes",
        displayName: "Worker Nodes",
        description: "Number of worker nodes",
        defaultValue: 3,
        min: 1,
        max: 100,
      },
      networkPlugin: {
        type: FIELD_TYPES.DROPDOWN,
        name: "networkPlugin",
        displayName: "Network Plugin",
        description: "Container network interface",
        defaultValue: "calico",
        options: [
          { value: "calico", label: "Calico" },
          { value: "flannel", label: "Flannel" },
          { value: "weave", label: "Weave Net" },
          { value: "cilium", label: "Cilium" },
        ],
      },
    },
  },

  monitoring: {
    name: "monitoring",
    displayName: "Monitoring Stack",
    description: "Prometheus and Grafana monitoring",
    provider: "onpremise",
    category: "Observability",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Monitoring",
        description: "Enable monitoring stack",
        defaultValue: false,
      },
      enablePrometheus: {
        type: FIELD_TYPES.TOGGLE,
        name: "enablePrometheus",
        displayName: "Prometheus",
        description: "Enable Prometheus metrics collection",
        defaultValue: true,
      },
      enableGrafana: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableGrafana",
        displayName: "Grafana",
        description: "Enable Grafana dashboards",
        defaultValue: true,
      },
      enableAlertmanager: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAlertmanager",
        displayName: "Alertmanager",
        description: "Enable alert management",
        defaultValue: true,
      },
      retentionDays: {
        type: FIELD_TYPES.NUMBER,
        name: "retentionDays",
        displayName: "Retention (days)",
        description: "Metrics retention period",
        defaultValue: 30,
        min: 1,
        max: 365,
      },
    },
  },

  logging: {
    name: "logging",
    displayName: "Logging Stack",
    description: "Centralized logging with ELK stack",
    provider: "onpremise",
    category: "Observability",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Logging",
        description: "Enable logging stack",
        defaultValue: false,
      },
      enableElasticsearch: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableElasticsearch",
        displayName: "Elasticsearch",
        description: "Enable Elasticsearch",
        defaultValue: true,
      },
      enableLogstash: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLogstash",
        displayName: "Logstash",
        description: "Enable Logstash",
        defaultValue: true,
      },
      enableKibana: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableKibana",
        displayName: "Kibana",
        description: "Enable Kibana dashboards",
        defaultValue: true,
      },
      enableFluentd: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableFluentd",
        displayName: "Fluentd",
        description: "Enable Fluentd log collection",
        defaultValue: true,
      },
    },
  },

  storage: {
    name: "storage",
    displayName: "Storage Solutions",
    description: "Persistent storage configuration",
    provider: "onpremise",
    category: "Storage",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Storage",
        description: "Enable storage solutions",
        defaultValue: false,
      },
      enableNFS: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableNFS",
        displayName: "NFS",
        description: "Enable NFS storage",
        defaultValue: false,
      },
      enableCeph: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableCeph",
        displayName: "Ceph",
        description: "Enable Ceph distributed storage",
        defaultValue: false,
      },
      enableLonghorn: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLonghorn",
        displayName: "Longhorn",
        description: "Enable Longhorn cloud-native storage",
        defaultValue: true,
      },
      replicationFactor: {
        type: FIELD_TYPES.NUMBER,
        name: "replicationFactor",
        displayName: "Replication Factor",
        description: "Storage replication factor",
        defaultValue: 3,
        min: 1,
        max: 5,
      },
    },
  },

  networking: {
    name: "networking",
    displayName: "Network Configuration",
    description: "Network infrastructure setup",
    provider: "onpremise",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Networking",
        description: "Enable network configuration",
        defaultValue: false,
      },
      enableLoadBalancer: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLoadBalancer",
        displayName: "Load Balancer",
        description: "Enable load balancer (MetalLB)",
        defaultValue: true,
      },
      enableIngress: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableIngress",
        displayName: "Ingress Controller",
        description: "Enable ingress controller",
        defaultValue: true,
      },
      ingressType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "ingressType",
        displayName: "Ingress Type",
        description: "Ingress controller type",
        defaultValue: "nginx",
        options: [
          { value: "nginx", label: "NGINX" },
          { value: "traefik", label: "Traefik" },
          { value: "haproxy", label: "HAProxy" },
        ],
      },
      enableSSL: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableSSL",
        displayName: "SSL/TLS",
        description: "Enable SSL/TLS certificates",
        defaultValue: true,
      },
    },
  },
};

export const getServiceConfig = (serviceName) => {
  return SERVICES_CONFIG[serviceName];
};

export const getServicesByProvider = (providerType) => {
  return Object.values(SERVICES_CONFIG).filter(
    (service) => service.provider === providerType,
  );
};

export const getServicesByCategory = (category) => {
  return Object.values(SERVICES_CONFIG).filter(
    (service) => service.category === category,
  );
};

export const createDefaultServiceConfig = (serviceName) => {
  const config = getServiceConfig(serviceName);
  if (!config) return {};

  const defaultConfig = {};
  for (const [fieldName, fieldConfig] of Object.entries(config.fields)) {
    defaultConfig[fieldName] = fieldConfig.defaultValue;
  }

  return defaultConfig;
};
