// src/config/services/azure.js
import { FIELD_TYPES } from "./fieldTypes";

export const azureServices = {
  vnet: {
    name: "vnet",
    displayName: "Virtual Network (VNet)",
    description: "Azure Virtual Network for network isolation",
    provider: "azure",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable VNet",
        description: "Enable VNet service",
        defaultValue: false,
      },
      addressSpace: {
        type: FIELD_TYPES.TEXT,
        name: "addressSpace",
        displayName: "Address Space",
        description: "The address space for the VNet",
        defaultValue: "10.0.0.0/16",
        validation: { pattern: /^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/ },
      },
      subnets: {
        type: FIELD_TYPES.OBJECT,
        name: "subnets",
        displayName: "Subnets",
        description: "Subnet configurations",
      },
      enableDdosProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableDdosProtection",
        displayName: "DDoS Protection",
        description: "Enable DDoS protection",
        defaultValue: false,
      },
      enableVmProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableVmProtection",
        displayName: "VM Protection",
        description: "Enable VM protection",
        defaultValue: false,
      },
    },
  },

  aks: {
    name: "aks",
    displayName: "Azure Kubernetes Service (AKS)",
    description: "Managed Kubernetes service from Azure",
    provider: "azure",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable AKS",
        description: "Enable AKS service",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      nodeGroups: {
        type: FIELD_TYPES.NUMBER,
        name: "nodeGroups",
        displayName: "Node Pools",
        description: "Number of node pools",
        defaultValue: 1,
        min: 1,
        max: 10,
      },
      minNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "minNodes",
        displayName: "Min Nodes",
        description: "Minimum number of nodes",
        defaultValue: 2,
        min: 1,
        max: 100,
      },
      maxNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "maxNodes",
        displayName: "Max Nodes",
        description: "Maximum number of nodes",
        defaultValue: 5,
        min: 1,
        max: 100,
      },
      vmSize: {
        type: FIELD_TYPES.DROPDOWN,
        name: "vmSize",
        displayName: "VM Size",
        description: "Azure VM size",
        defaultValue: "Standard_D2s_v3",
        options: [
          { value: "Standard_B2s", label: "Standard_B2s" },
          { value: "Standard_D2s_v3", label: "Standard_D2s_v3" },
          { value: "Standard_D4s_v3", label: "Standard_D4s_v3" },
          { value: "Standard_D8s_v3", label: "Standard_D8s_v3" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "OS disk size in GB",
        defaultValue: 50,
        min: 30,
        max: 1000,
      },
      enableAutoScaling: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutoScaling",
        displayName: "Auto Scaling",
        description: "Enable node auto scaling",
        defaultValue: true,
      },
      enableClusterAutoscaler: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableClusterAutoscaler",
        displayName: "Cluster Autoscaler",
        description: "Enable cluster autoscaler",
        defaultValue: false,
      },
      enableMetricsServer: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableMetricsServer",
        displayName: "Metrics Server",
        description: "Enable metrics server",
        defaultValue: true,
      },
      addons: {
        type: FIELD_TYPES.OBJECT,
        name: "addons",
        displayName: "AKS Addons",
        description: "AKS managed addons",
      },
    },
  },

  sqlDatabase: {
    name: "sqlDatabase",
    displayName: "Azure SQL Database",
    description: "Managed SQL database service",
    provider: "azure",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable SQL Database",
        description: "Enable Azure SQL Database",
        defaultValue: false,
      },
      tier: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tier",
        displayName: "Service Tier",
        description: "Database service tier",
        defaultValue: "Basic",
        options: [
          { value: "Basic", label: "Basic" },
          { value: "Standard", label: "Standard" },
          { value: "Premium", label: "Premium" },
          { value: "GeneralPurpose", label: "General Purpose" },
          { value: "BusinessCritical", label: "Business Critical" },
        ],
      },
      size: {
        type: FIELD_TYPES.TEXT,
        name: "size",
        displayName: "Compute Size",
        description: "Database compute size",
        defaultValue: "S0",
      },
      maxStorage: {
        type: FIELD_TYPES.NUMBER,
        name: "maxStorage",
        displayName: "Max Storage (GB)",
        description: "Maximum storage in GB",
        defaultValue: 2,
        min: 1,
        max: 1000,
      },
      enableBackup: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableBackup",
        displayName: "Automated Backup",
        description: "Enable automated backup",
        defaultValue: true,
      },
      backupRetention: {
        type: FIELD_TYPES.NUMBER,
        name: "backupRetention",
        displayName: "Backup Retention (days)",
        description: "Backup retention period in days",
        defaultValue: 7,
        min: 1,
        max: 35,
      },
      enableEncryption: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableEncryption",
        displayName: "Encryption",
        description: "Enable encryption at rest",
        defaultValue: true,
      },
      enableAdvancedThreatProtection: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAdvancedThreatProtection",
        displayName: "Advanced Threat Protection",
        description: "Enable advanced threat protection",
        defaultValue: false,
      },
      enableAudit: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAudit",
        displayName: "Auditing",
        description: "Enable database auditing",
        defaultValue: false,
      },
    },
  },
};
