// src/config/services/gcp.js
import { FIELD_TYPES } from "./fieldTypes";

export const gcpServices = {
  gke: {
    name: "gke",
    displayName: "Google Kubernetes Engine (GKE)",
    description: "Managed Kubernetes service from Google Cloud",
    provider: "gcp",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable GKE",
        description: "Enable GKE service",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      nodeCount: {
        type: FIELD_TYPES.NUMBER,
        name: "nodeCount",
        displayName: "Node Count",
        description: "Number of nodes",
        defaultValue: 3,
        min: 1,
        max: 100,
      },
      machineType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "machineType",
        displayName: "Machine Type",
        description: "GCE machine type",
        defaultValue: "e2-medium",
        options: [
          { value: "e2-micro", label: "e2-micro" },
          { value: "e2-small", label: "e2-small" },
          { value: "e2-medium", label: "e2-medium" },
          { value: "e2-standard-2", label: "e2-standard-2" },
          { value: "e2-standard-4", label: "e2-standard-4" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "Boot disk size in GB",
        defaultValue: 50,
        min: 20,
        max: 1000,
      },
      enableAutoScaling: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutoScaling",
        displayName: "Auto Scaling",
        description: "Enable node auto scaling",
        defaultValue: true,
      },
      enableAutopilot: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAutopilot",
        displayName: "Autopilot Mode",
        description: "Enable GKE Autopilot",
        defaultValue: false,
      },
    },
  },

  cloudSql: {
    name: "cloudSql",
    displayName: "Cloud SQL",
    description: "Managed relational database service",
    provider: "gcp",
    category: "Database",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Cloud SQL",
        description: "Enable Cloud SQL service",
        defaultValue: false,
      },
      databaseVersion: {
        type: FIELD_TYPES.DROPDOWN,
        name: "databaseVersion",
        displayName: "Database Version",
        description: "Database engine and version",
        defaultValue: "POSTGRES_15",
        options: [
          { value: "POSTGRES_15", label: "PostgreSQL 15" },
          { value: "POSTGRES_14", label: "PostgreSQL 14" },
          { value: "MYSQL_8_0", label: "MySQL 8.0" },
          { value: "MYSQL_5_7", label: "MySQL 5.7" },
        ],
      },
      tier: {
        type: FIELD_TYPES.DROPDOWN,
        name: "tier",
        displayName: "Machine Type",
        description: "Instance tier",
        defaultValue: "db-n1-standard-1",
        options: [
          { value: "db-f1-micro", label: "db-f1-micro" },
          { value: "db-g1-small", label: "db-g1-small" },
          { value: "db-n1-standard-1", label: "db-n1-standard-1" },
          { value: "db-n1-standard-2", label: "db-n1-standard-2" },
        ],
      },
      diskSize: {
        type: FIELD_TYPES.NUMBER,
        name: "diskSize",
        displayName: "Disk Size (GB)",
        description: "Storage size in GB",
        defaultValue: 10,
        min: 10,
        max: 1000,
      },
      enableBackup: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableBackup",
        displayName: "Automated Backup",
        description: "Enable automated backup",
        defaultValue: true,
      },
      enableHighAvailability: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableHighAvailability",
        displayName: "High Availability",
        description: "Enable high availability",
        defaultValue: false,
      },
    },
  },
};
