// src/config/services/onprem.js
import { FIELD_TYPES } from "./fieldTypes";

export const onpremServices = {
  kubernetes: {
    name: "kubernetes",
    displayName: "Kubernetes Cluster",
    description: "Self-managed Kubernetes cluster",
    provider: "onpremise",
    category: "Compute",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Kubernetes",
        description: "Enable Kubernetes cluster",
        defaultValue: false,
      },
      version: {
        type: FIELD_TYPES.DROPDOWN,
        name: "version",
        displayName: "Kubernetes Version",
        description: "Kubernetes version",
        defaultValue: "1.28",
        options: [
          { value: "1.26", label: "1.26" },
          { value: "1.27", label: "1.27" },
          { value: "1.28", label: "1.28" },
          { value: "1.29", label: "1.29" },
        ],
      },
      masterNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "masterNodes",
        displayName: "Master Nodes",
        description: "Number of master nodes",
        defaultValue: 3,
        min: 1,
        max: 10,
      },
      workerNodes: {
        type: FIELD_TYPES.NUMBER,
        name: "workerNodes",
        displayName: "Worker Nodes",
        description: "Number of worker nodes",
        defaultValue: 3,
        min: 1,
        max: 100,
      },
      networkPlugin: {
        type: FIELD_TYPES.DROPDOWN,
        name: "networkPlugin",
        displayName: "Network Plugin",
        description: "Container network interface",
        defaultValue: "calico",
        options: [
          { value: "calico", label: "Calico" },
          { value: "flannel", label: "Flannel" },
          { value: "weave", label: "Weave Net" },
          { value: "cilium", label: "Cilium" },
        ],
      },
    },
  },

  monitoring: {
    name: "monitoring",
    displayName: "Monitoring Stack",
    description: "Prometheus and Grafana monitoring",
    provider: "onpremise",
    category: "Observability",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Monitoring",
        description: "Enable monitoring stack",
        defaultValue: false,
      },
      enablePrometheus: {
        type: FIELD_TYPES.TOGGLE,
        name: "enablePrometheus",
        displayName: "Prometheus",
        description: "Enable Prometheus metrics collection",
        defaultValue: true,
      },
      enableGrafana: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableGrafana",
        displayName: "Grafana",
        description: "Enable Grafana dashboards",
        defaultValue: true,
      },
      enableAlertmanager: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableAlertmanager",
        displayName: "Alertmanager",
        description: "Enable alert management",
        defaultValue: true,
      },
      retentionDays: {
        type: FIELD_TYPES.NUMBER,
        name: "retentionDays",
        displayName: "Retention (days)",
        description: "Metrics retention period",
        defaultValue: 30,
        min: 1,
        max: 365,
      },
    },
  },

  logging: {
    name: "logging",
    displayName: "Logging Stack",
    description: "Centralized logging with ELK stack",
    provider: "onpremise",
    category: "Observability",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Logging",
        description: "Enable logging stack",
        defaultValue: false,
      },
      enableElasticsearch: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableElasticsearch",
        displayName: "Elasticsearch",
        description: "Enable Elasticsearch",
        defaultValue: true,
      },
      enableLogstash: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLogstash",
        displayName: "Logstash",
        description: "Enable Logstash",
        defaultValue: true,
      },
      enableKibana: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableKibana",
        displayName: "Kibana",
        description: "Enable Kibana dashboards",
        defaultValue: true,
      },
      enableFluentd: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableFluentd",
        displayName: "Fluentd",
        description: "Enable Fluentd log collection",
        defaultValue: true,
      },
    },
  },

  storage: {
    name: "storage",
    displayName: "Storage Solutions",
    description: "Persistent storage configuration",
    provider: "onpremise",
    category: "Storage",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Storage",
        description: "Enable storage solutions",
        defaultValue: false,
      },
      enableNFS: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableNFS",
        displayName: "NFS",
        description: "Enable NFS storage",
        defaultValue: false,
      },
      enableCeph: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableCeph",
        displayName: "Ceph",
        description: "Enable Ceph distributed storage",
        defaultValue: false,
      },
      enableLonghorn: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLonghorn",
        displayName: "Longhorn",
        description: "Enable Longhorn cloud-native storage",
        defaultValue: true,
      },
      replicationFactor: {
        type: FIELD_TYPES.NUMBER,
        name: "replicationFactor",
        displayName: "Replication Factor",
        description: "Storage replication factor",
        defaultValue: 3,
        min: 1,
        max: 5,
      },
    },
  },

  networking: {
    name: "networking",
    displayName: "Network Configuration",
    description: "Network infrastructure setup",
    provider: "onpremise",
    category: "Networking",
    fields: {
      enabled: {
        type: FIELD_TYPES.TOGGLE,
        name: "enabled",
        displayName: "Enable Networking",
        description: "Enable network configuration",
        defaultValue: false,
      },
      enableLoadBalancer: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableLoadBalancer",
        displayName: "Load Balancer",
        description: "Enable load balancer (MetalLB)",
        defaultValue: true,
      },
      enableIngress: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableIngress",
        displayName: "Ingress Controller",
        description: "Enable ingress controller",
        defaultValue: true,
      },
      ingressType: {
        type: FIELD_TYPES.DROPDOWN,
        name: "ingressType",
        displayName: "Ingress Type",
        description: "Ingress controller type",
        defaultValue: "nginx",
        options: [
          { value: "nginx", label: "NGINX" },
          { value: "traefik", label: "Traefik" },
          { value: "haproxy", label: "HAProxy" },
        ],
      },
      enableSSL: {
        type: FIELD_TYPES.TOGGLE,
        name: "enableSSL",
        displayName: "SSL/TLS",
        description: "Enable SSL/TLS certificates",
        defaultValue: true,
      },
    },
  },
};
